package warehouse

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"time"

	// DuckDB is the single Parquet implementation in the process. Writing with
	// one library and reading with another is how two readers of the same file
	// come to disagree, so there is only ever one.
	_ "github.com/marcboeker/go-duckdb"
)

// Row is one materialized record. The warehouse package deliberately does not
// depend on the connectors package — connectors depends on this one — so rows
// cross the boundary as plain maps.
type Row = map[string]any

// ParquetCompression is the codec every table is written with. zstd was
// measured 17.4x smaller than the JSONL it replaces on a real corpus, and
// DuckDB decompresses it natively with no extension to install.
const ParquetCompression = "zstd"

// TableWriter materializes one table as a single Parquet file.
//
// Rows are streamed to a staging log and converted in one pass on Commit, so a
// table larger than memory still materializes: the previous JSONL append path
// streamed, and replacing it with something that buffers every row would be a
// regression dressed up as a format change.
//
// A table with no rows commits a zero-byte file rather than nothing. That is
// what the JSONL materialization did, and it is what keeps a zero-row sync
// from telling an operator the table does not exist. Every reader here treats
// a zero-byte table as zero rows; no schema is invented for rows never seen.
type TableWriter struct {
	path    string
	staging string
	temp    string
	file    *os.File
	encoder *json.Encoder
	rows    int
	closed  bool
}

// NewTableWriter opens a writer for the table at path. The table already in
// place is untouched until Commit succeeds.
func NewTableWriter(path string) (*TableWriter, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, fmt.Errorf("create warehouse tables directory: %w", err)
	}
	staging := path + ".staging.jsonl"
	file, err := os.OpenFile(staging, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return nil, fmt.Errorf("stage warehouse table: %w", err)
	}
	return &TableWriter{
		path:    path,
		staging: staging,
		temp:    path + ".tmp",
		file:    file,
		encoder: json.NewEncoder(file),
	}, nil
}

// Write stages one row.
func (w *TableWriter) Write(row Row) error {
	if w.closed {
		return errors.New("warehouse table writer is closed")
	}
	if err := w.encoder.Encode(row); err != nil {
		return fmt.Errorf("encode warehouse row: %w", err)
	}
	w.rows++
	return nil
}

// Rows reports how many rows have been staged.
func (w *TableWriter) Rows() int { return w.rows }

// Commit converts the staged rows to Parquet and moves the result into place
// with a single rename. A table is one file precisely so this rename is
// atomic: a directory of parts cannot be renamed over an existing directory,
// and the two-rename workaround opens a window in which a reader sees no table
// at all while its rows sit intact on disk.
func (w *TableWriter) Commit(ctx context.Context) error {
	if w.closed {
		return errors.New("warehouse table writer is closed")
	}
	w.closed = true
	defer func() {
		_ = os.Remove(w.staging)
		_ = os.Remove(w.temp)
	}()
	if err := w.file.Close(); err != nil {
		return fmt.Errorf("close staged warehouse table: %w", err)
	}
	if w.rows == 0 {
		if err := writeEmptyFile(w.temp); err != nil {
			return err
		}
		return replaceTable(w.temp, w.path)
	}

	db, err := sql.Open("duckdb", "")
	if err != nil {
		return fmt.Errorf("open duckdb: %w", err)
	}
	defer func() { _ = db.Close() }()
	// sample_size=-1 makes schema inference read every staged row instead of a
	// bounded prefix. The default prefix is 20,480 rows, and a connector field
	// that is sparse — or that a provider started sending partway through a
	// backfill — first appears after it. With the default the whole sync fails
	// on `has unknown key`, so a table larger than the sample is not
	// materializable at all; the cost of reading every row is one extra pass
	// over a file already on disk.
	//
	// Both paths are generated by this package and validated component by
	// component before they are joined; neither carries user SQL. They are
	// still passed as escaped string literals rather than interpolated.
	statement := fmt.Sprintf(
		`COPY (SELECT * FROM read_json_auto('%s', sample_size=-1)) TO '%s' (FORMAT parquet, COMPRESSION %s)`,
		escapeSQLLiteral(w.staging), escapeSQLLiteral(w.temp), ParquetCompression,
	)
	if _, err := db.ExecContext(ctx, statement); err != nil {
		return fmt.Errorf("write parquet table %s: %w", filepath.Base(w.path), err)
	}
	return replaceTable(w.temp, w.path)
}

// Abort discards the staged rows and leaves the table already in place
// untouched. It is safe to call after Commit.
func (w *TableWriter) Abort() {
	if !w.closed {
		w.closed = true
		_ = w.file.Close()
	}
	_ = os.Remove(w.staging)
	_ = os.Remove(w.temp)
}

// WriteTable materializes rows as a single Parquet file at path, replacing
// whatever is there. It is the convenience form for callers that already hold
// every row; streaming producers use TableWriter directly.
func WriteTable(ctx context.Context, path string, rows []Row) error {
	writer, err := NewTableWriter(path)
	if err != nil {
		return err
	}
	for _, row := range rows {
		if err := ctx.Err(); err != nil {
			writer.Abort()
			return err
		}
		if err := writer.Write(row); err != nil {
			writer.Abort()
			return err
		}
	}
	return writer.Commit(ctx)
}

// ReadTable emits every row of a materialized Parquet table. It stops early,
// returning emit's error, when emit reports one — that is how a limited read
// stops without materializing the rest.
func ReadTable(ctx context.Context, path string, emit func(Row) error) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("open warehouse table %s: %w", filepath.Base(path), err)
	}
	// A zero-byte table is an empty table, not a damaged one. It is what a
	// sync that loaded no rows leaves behind.
	if info.Size() == 0 {
		return nil
	}
	db, err := sql.Open("duckdb", "")
	if err != nil {
		return fmt.Errorf("open duckdb: %w", err)
	}
	defer func() { _ = db.Close() }()
	rows, err := db.QueryContext(ctx, fmt.Sprintf(`SELECT * FROM read_parquet('%s')`, escapeSQLLiteral(path)))
	if err != nil {
		return fmt.Errorf("read warehouse table %s: %w", filepath.Base(path), err)
	}
	defer func() { _ = rows.Close() }()
	columns, err := rows.Columns()
	if err != nil {
		return fmt.Errorf("read warehouse table columns: %w", err)
	}
	holders := make([]any, len(columns))
	targets := make([]any, len(columns))
	for i := range holders {
		targets[i] = &holders[i]
	}
	for rows.Next() {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := rows.Scan(targets...); err != nil {
			return fmt.Errorf("scan warehouse row: %w", err)
		}
		row := make(Row, len(columns))
		for i, column := range columns {
			row[column] = NormalizeValue(holders[i])
		}
		if err := emit(row); err != nil {
			return err
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate warehouse table %s: %w", filepath.Base(path), err)
	}
	return nil
}

func writeEmptyFile(path string) error {
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("create warehouse table: %w", err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("close warehouse table: %w", err)
	}
	return nil
}

// replaceTable fsyncs the freshly written table and moves it into place.
//
// The handle is opened read-write purely so the sync is portable: Windows
// implements File.Sync as FlushFileBuffers, which refuses a handle without
// write access. A read-only open works on Unix and would fail only on Windows.
func replaceTable(temp, path string) error {
	file, err := os.OpenFile(temp, os.O_RDWR, 0o600)
	if err != nil {
		return fmt.Errorf("open written warehouse table: %w", err)
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return fmt.Errorf("sync warehouse table: %w", err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("close warehouse table: %w", err)
	}
	if err := os.Rename(temp, path); err != nil {
		return fmt.Errorf("replace warehouse table: %w", err)
	}
	return nil
}

// EscapeSQLLiteral escapes single quotes for safe inclusion inside a single
// quoted SQL string literal. It is exported so the query engine shares this one
// implementation rather than carrying its own copy.
func EscapeSQLLiteral(value string) string { return escapeSQLLiteral(value) }

func escapeSQLLiteral(value string) string {
	return strings.ReplaceAll(value, "'", "''")
}

// NormalizeValue coerces DuckDB driver values into the JSON-shaped Go types the
// rest of pm passes around, so a row read from a table is interchangeable with
// one that came straight off a connector. DuckDB returns wide integers
// (HUGEINT, e.g. from SUM) as *big.Int; those collapse to int64 when they fit
// and to float64 when they do not.
func NormalizeValue(value any) any {
	switch typed := value.(type) {
	case []byte:
		return string(typed)
	case time.Time:
		return typed.Format(time.RFC3339)
	case *big.Int:
		if typed == nil {
			return nil
		}
		if typed.IsInt64() {
			return typed.Int64()
		}
		out, _ := new(big.Float).SetInt(typed).Float64()
		return out
	case big.Int:
		return NormalizeValue(&typed)
	case uint64:
		if typed <= math.MaxInt64 {
			return int64(typed)
		}
		return float64(typed)
	default:
		return typed
	}
}
