#!/usr/bin/env sh
set -eu

export GOTOOLCHAIN="${GOTOOLCHAIN:-auto}"

gofmt -w cmd internal
make test TEST_PACKAGES="./internal/connectors ./internal/cli ./cmd/iconregistrygen"
go build ./cmd/pm
./pm docs validate --connectors-dir docs/connectors
