directive @preview(toggledBy: String!) on FIELD_DEFINITION
directive @deprecated(reason: String) on FIELD_DEFINITION

interface Node {
  id: ID!
}

enum WidgetCloseReason {
  DONE
  STALE
}

input CreateEnterpriseOrganizationInput {
  enterpriseAdmin: String!
  login: String!
  profileName: String!
}

input CloseWidgetInput {
  widgetId: ID!
  reason: WidgetCloseReason
}

type CreateEnterpriseOrganizationPayload {
  clientMutationId: String
}

type CloseWidgetPayload {
  clientMutationId: String
  widget: Widget
}

type User implements Node {
  id: ID!
  login: String!
}

type Widget implements Node {
  id: ID!
  name: String!
}

union SearchResult = User | Widget

type Mutation {
  createEnterpriseOrganization(
    input: CreateEnterpriseOrganizationInput!
  ): CreateEnterpriseOrganizationPayload @preview(toggledBy: "enterprise-admin")

  closeWidget(input: CloseWidgetInput!): CloseWidgetPayload
}

type Query {
  viewer: User!

  node(id: ID!): Node

  nodes(ids: [ID!]!): [Node]!

  widget(
    owner: String!
    name: String!
  ): Widget @deprecated(reason: "use node")
}
