// Code generated by connectorgen gen. DO NOT EDIT.
package mixpanel

import "polymetrics.ai/internal/connectors/engine"

// ExplicitFactory constructs this package's registered hook without global lookup.
func ExplicitFactory() engine.Hooks { return New() }
