package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const modulePath = "polymetrics.ai"

// genHookset regenerates hooks/hookset/hookset_gen.go under hooksRoot: a
// blank import for every internal/connectors/hooks/<name> package except
// hookset itself. Deterministic and byte-stable across reruns for the same
// input tree (sorted package names, fixed header text, no timestamps).
func genHookset(hooksRoot string) error {
	pkgs, err := wiringPackageNames(hooksRoot, "hookset")
	if err != nil {
		return fmt.Errorf("gen hookset: %w", err)
	}
	src := renderWiringFile(wiringFileSpec{
		Package:     "hookset",
		ImportsDoc:  "Package hookset blank-imports every internal/connectors/hooks/<name>\n// package so their init() functions run engine.RegisterHooks side effects.",
		ImportsRoot: modulePath + "/internal/connectors/hooks",
		Packages:    pkgs,
	})
	return writeGenFile(filepath.Join(hooksRoot, "hookset", "hookset_gen.go"), src)
}

// genNativeset regenerates native/nativeset/nativeset_gen.go under
// nativeRoot: a blank import for every internal/connectors/native/<name>
// package except nativeset itself.
func genNativeset(nativeRoot string) error {
	pkgs, err := wiringPackageNames(nativeRoot, "nativeset")
	if err != nil {
		return fmt.Errorf("gen nativeset: %w", err)
	}
	src := renderWiringFile(wiringFileSpec{
		Package:     "nativeset",
		ImportsDoc:  "Package nativeset blank-imports every internal/connectors/native/<name>\n// Tier-3 component package so any package-level side effects (e.g. a\n// future documented registration) run in the built binary. In wave0 no\n// native package registers itself (see API-CONTRACT.md §6); this file is\n// pure wiring, regenerated deterministically as packages are added.",
		ImportsRoot: modulePath + "/internal/connectors/native",
		Packages:    pkgs,
	})
	return writeGenFile(filepath.Join(nativeRoot, "nativeset", "nativeset_gen.go"), src)
}

// wiringPackageNames returns the sorted directory names under root that are
// NOT selfName and are plain directories (no further filtering: package
// declaration sniffing is unnecessary for wave0's empty-or-single-package
// trees and would only add a false sense of precision — a directory without
// a .go file simply produces an import that fails to build, which is the
// correct, loud failure mode for a malformed hooks/native tree).
func wiringPackageNames(root, selfName string) ([]string, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", root, err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() || e.Name() == selfName {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)
	return names, nil
}

// wiringFileSpec parametrizes the two near-identical generated wiring files.
type wiringFileSpec struct {
	Package     string
	ImportsDoc  string
	ImportsRoot string
	Packages    []string
}

// renderWiringFile deterministically renders a "Code generated" wiring file:
// fixed header, package clause, blank imports (or none), and nothing else —
// no timestamps or non-deterministic ordering.
func renderWiringFile(spec wiringFileSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by connectorgen gen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// " + spec.ImportsDoc + "\n")
	b.WriteString("// It is regenerated deterministically by `go run ./cmd/connectorgen gen`.\n")
	b.WriteString("package " + spec.Package + "\n")

	if len(spec.Packages) == 0 {
		return b.String()
	}

	b.WriteString("\n")
	b.WriteString("import (\n")
	for _, pkg := range spec.Packages {
		b.WriteString("\t_ \"" + spec.ImportsRoot + "/" + pkg + "\"\n")
	}
	b.WriteString(")\n")
	return b.String()
}

// writeGenFile writes src to path, creating parent directories as needed.
func writeGenFile(path, src string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// runGen implements `connectorgen gen` against the real repo layout rooted
// at repoRoot (found by walking up to go.mod).
func runGen(args []string, stdout, stderr io.Writer) int {
	root, err := repoRoot()
	if err != nil {
		logln(stderr, "connectorgen gen:", err)
		return 1
	}
	return runGenAt(args, stdout, stderr,
		filepath.Join(root, "internal/connectors/hooks"),
		filepath.Join(root, "internal/connectors/native"),
	)
}

// runGenAt is runGen with explicit hooks/native roots, used directly by
// tests against scratch trees.
func runGenAt(_ []string, stdout, stderr io.Writer, hooksRoot, nativeRoot string) int {
	if err := genHookset(hooksRoot); err != nil {
		logln(stderr, "connectorgen gen:", err)
		return 1
	}
	if err := genNativeset(nativeRoot); err != nil {
		logln(stderr, "connectorgen gen:", err)
		return 1
	}
	logln(stdout, "connectorgen gen: wrote hookset_gen.go and nativeset_gen.go")
	return 0
}
