package main

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"polymetrics.ai/internal/connectors/engine"
)

func TestSourceMaterialize_HappyBundleAndByteIdenticalCheck(t *testing.T) {
	defsRoot, lockRaw, fetcher := sourceMaterializeFixture(t, sourceMaterializeFixtureOptions{})
	stderr := new(bytes.Buffer)
	if code := runSourceMaterializeWithFetcher([]string{"source-materialize", "alpha", "--defs", defsRoot}, new(bytes.Buffer), stderr, fetcher); code != 0 {
		t.Fatalf("materialize exit code = %d stderr=%s", code, stderr.String())
	}
	bundleDir := filepath.Join(defsRoot, "alpha")
	for _, name := range []string{"metadata.json", "spec.json", "streams.json", "writes.json", "operations.json", "api_surface.json", "cli_surface.json", "docs.md", "missing-foundation.json", filepath.Join("sources", "alpha-operation-descriptor.json")} {
		if _, err := os.Stat(filepath.Join(bundleDir, name)); err != nil {
			t.Fatalf("generated %s: %v", name, err)
		}
	}
	if _, err := engine.Load(os.DirFS(defsRoot), "alpha"); err != nil {
		t.Fatalf("generated bundle does not load: %v", err)
	}
	if findings, err := validateOperationalContractPath(bundleDir, "alpha", "declared"); err != nil || len(findings) != 0 {
		t.Fatalf("declared operational contract = findings=%+v err=%v", findings, err)
	}
	before := sourceMaterializeOwnedBytes(t, bundleDir)
	stdout, stderr := new(bytes.Buffer), new(bytes.Buffer)
	if code := runSourceMaterializeWithFetcher([]string{"source-materialize", "alpha", "--defs", defsRoot, "--check"}, stdout, stderr, fetcher); code != 0 {
		t.Fatalf("byte-identical check exit = %d stderr=%s", code, stderr.String())
	}
	after := sourceMaterializeOwnedBytes(t, bundleDir)
	if !bytes.Equal(before, after) {
		t.Fatalf("--check changed owned output bytes\nbefore=%q\nafter=%q\nlock=%s", before, after, lockRaw)
	}
}

func TestSourceMaterialize_EdgeUsesExactRetainedSourceURLs(t *testing.T) {
	defsRoot, _, fetcher := sourceMaterializeFixture(t, sourceMaterializeFixtureOptions{})
	var requested []string
	recordingFetcher := sourceImportFetchFunc(func(ctx context.Context, sourceURL string) ([]byte, error) {
		requested = append(requested, sourceURL)
		return fetcher.Fetch(ctx, sourceURL)
	})
	stderr := new(bytes.Buffer)
	if code := runSourceMaterializeWithFetcher([]string{"source-materialize", "alpha", "--defs", defsRoot}, new(bytes.Buffer), stderr, recordingFetcher); code != 0 {
		t.Fatalf("materialize exit = %d stderr=%s", code, stderr.String())
	}
	want := []string{
		"https://fixtures.polymetrics.invalid/get.openapi.json",
		"https://fixtures.polymetrics.invalid/post.openapi.json",
	}
	if !reflect.DeepEqual(requested, want) {
		t.Fatalf("retained source URLs = %#v, want %#v", requested, want)
	}
}

func TestSourceMaterialize_RejectsBadV4Plans(t *testing.T) {
	tests := []struct {
		name      string
		options   sourceMaterializeFixtureOptions
		wantError string
	}{
		{name: "legacy lock requires v4", options: sourceMaterializeFixtureOptions{Legacy: true}, wantError: "schema v4"},
		{name: "unknown materialization field", options: sourceMaterializeFixtureOptions{UnknownMaterializationField: true}, wantError: "unknown field"},
		{name: "duplicate source accounting", options: sourceMaterializeFixtureOptions{DuplicateAccounting: true}, wantError: "duplicate source operation ID"},
		{name: "required body input lacks binding", options: sourceMaterializeFixtureOptions{MissingBodyBinding: true}, wantError: "required input \"body.title\""},
		{name: "unselected request media arm", options: sourceMaterializeFixtureOptions{WrongRequestMedia: true, MultipleMedia: true}, wantError: "not the selected JSON mutation contract"},
		{name: "owned output symlink escape", options: sourceMaterializeFixtureOptions{OutputSymlink: true}, wantError: "must not traverse a symlink"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defsRoot, _, fetcher := sourceMaterializeFixture(t, tt.options)
			stderr := new(bytes.Buffer)
			code := runSourceMaterializeWithFetcher([]string{"source-materialize", "alpha", "--defs", defsRoot}, new(bytes.Buffer), stderr, fetcher)
			if code == 0 || !strings.Contains(stderr.String(), tt.wantError) {
				t.Fatalf("exit/stderr = %d/%q, want failure containing %q", code, stderr.String(), tt.wantError)
			}
		})
	}
}

func TestSourceMaterialize_AtomicNoWriteOnLateFailure(t *testing.T) {
	defsRoot, _, _ := sourceMaterializeFixture(t, sourceMaterializeFixtureOptions{})
	bundleDir := filepath.Join(defsRoot, "alpha")
	sentinel := []byte(`{"sentinel":"original"}\n`)
	if err := os.WriteFile(filepath.Join(bundleDir, "metadata.json"), sentinel, 0o644); err != nil {
		t.Fatalf("seed existing owned output: %v", err)
	}
	// The source-materializer stages generated bytes before calling the same
	// loader/check suite used by production. Invalid staged metadata therefore
	// reaches a genuinely late failure, after every staged write but before the
	// bundle-directory rename.
	err := sourceMaterializePublish(bundleDir, "alpha", []sourceMaterializeOutput{{RelativePath: "metadata.json", Bytes: []byte(`{}`)}})
	if err == nil || !strings.Contains(err.Error(), "load staged bundle") {
		t.Fatalf("late staged failure = %v, want staged loader failure", err)
	}
	got, err := os.ReadFile(filepath.Join(bundleDir, "metadata.json"))
	if err != nil || !bytes.Equal(got, sentinel) {
		t.Fatalf("atomic failure changed original metadata: got=%q err=%v", got, err)
	}
}

func TestValidate_OperationalContractGateIsOptIn(t *testing.T) {
	defsRoot, _, fetcher := sourceMaterializeFixture(t, sourceMaterializeFixtureOptions{})
	stderr := new(bytes.Buffer)
	if code := runSourceMaterializeWithFetcher([]string{"source-materialize", "alpha", "--defs", defsRoot}, new(bytes.Buffer), stderr, fetcher); code != 0 {
		t.Fatalf("materialize exit = %d stderr=%s", code, stderr.String())
	}
	validateStderr := new(bytes.Buffer)
	validateStdout := new(bytes.Buffer)
	ordinaryCode := run([]string{"validate", filepath.Join(defsRoot, "alpha")}, validateStdout, validateStderr)
	// A v4 lock is intentionally outside the legacy source-projection mapper,
	// so preserve validate's existing source-projection result verbatim. The
	// opt-in flag must neither alter that result nor enable anything globally.
	connectorStdout, connectorStderr := new(bytes.Buffer), new(bytes.Buffer)
	connectorCode := run([]string{"validate", filepath.Join(defsRoot, "alpha"), "--connector", "alpha"}, connectorStdout, connectorStderr)
	if connectorCode != ordinaryCode || connectorStdout.String() != validateStdout.String() || connectorStderr.String() != validateStderr.String() {
		t.Fatalf("connector selection changed ordinary validate: before=%d/%q/%q after=%d/%q/%q", ordinaryCode, validateStdout.String(), validateStderr.String(), connectorCode, connectorStdout.String(), connectorStderr.String())
	}
	gateStdout, gateStderr := new(bytes.Buffer), new(bytes.Buffer)
	gateCode := run([]string{"validate", filepath.Join(defsRoot, "alpha"), "--connector", "alpha", "--require-operational-contract", "write"}, gateStdout, gateStderr)
	if gateCode != ordinaryCode || gateStdout.String() != validateStdout.String() || gateStderr.String() != validateStderr.String() {
		t.Fatalf("satisfied opt-in write gate changed validate result: before=%d/%q/%q after=%d/%q/%q", ordinaryCode, validateStdout.String(), validateStderr.String(), gateCode, gateStdout.String(), gateStderr.String())
	}
	invalidStderr := new(bytes.Buffer)
	if code := run([]string{"validate", filepath.Join(defsRoot, "alpha"), "--connector", "alpha", "--require-operational-contract", "query"}, new(bytes.Buffer), invalidStderr); code != 1 || !strings.Contains(invalidStderr.String(), "operational contract profile") {
		t.Fatalf("invalid profile = %d/%q, want operational-contract failure", code, invalidStderr.String())
	}
}

type sourceMaterializeFixtureOptions struct {
	Legacy                      bool
	UnknownMaterializationField bool
	DuplicateAccounting         bool
	MissingBodyBinding          bool
	WrongRequestMedia           bool
	MultipleMedia               bool
	OutputSymlink               bool
}

func sourceMaterializeFixture(t *testing.T, options sourceMaterializeFixtureOptions) (string, []byte, sourceImportFetchFunc) {
	t.Helper()
	defsRoot := t.TempDir()
	sourcesDir := filepath.Join(defsRoot, "alpha", "sources")
	if err := os.MkdirAll(sourcesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	getRaw := []byte(`{"openapi":"3.0.3","info":{"title":"alpha","version":"1"},"paths":{"/widgets":{"get":{"operationId":"listWidgets","responses":{"200":{"description":"ok","content":{"application/json":{"schema":{"type":"object","additionalProperties":false,"properties":{"items":{"type":"array","items":{"type":"string"}}}}}}}}}}}}`)
	postSchema := map[string]any{"type": "object", "additionalProperties": false, "required": []any{"title"}, "properties": map[string]any{"title": map[string]any{"type": "string", "maxLength": 64}}}
	postContent := map[string]any{"application/json": map[string]any{"schema": postSchema}}
	if options.MultipleMedia {
		postContent["application/xml"] = map[string]any{"schema": postSchema}
	}
	postDocument := map[string]any{
		"openapi": "3.0.3",
		"info":    map[string]any{"title": "alpha", "version": "1"},
		"paths": map[string]any{
			"/widgets": map[string]any{
				"post": map[string]any{
					"operationId": "createWidget",
					"requestBody": map[string]any{"required": true, "content": postContent},
					"responses": map[string]any{
						"201": map[string]any{
							"description": "created",
							"content": map[string]any{
								"application/json": map[string]any{
									"schema": map[string]any{"type": "object", "additionalProperties": false},
								},
							},
						},
					},
				},
			},
		},
	}
	postRaw, err := json.Marshal(postDocument)
	if err != nil {
		t.Fatal(err)
	}
	getID, postID := "alpha.rest.get.shared", "alpha.rest.post.shared"
	plan := map[string]any{
		"metadata": map[string]any{"display_name": "Alpha", "description": "Alpha fixture connector.", "integration_type": "api", "release_stage": "preview", "docs_url": "https://docs.example.invalid/alpha"},
		"config": map[string]any{"properties": []any{
			map[string]any{"name": "base_url", "type": "string", "format": "uri", "description": "Provider origin.", "default": "https://api.example.invalid"},
			map[string]any{"name": "token", "type": "string", "description": "Bearer token.", "secret": true},
		}},
		"auth":   map[string]any{"mode": "bearer", "token": "{{ secrets.token }}"},
		"server": map[string]any{"url": "{{ config.base_url }}", "user_agent": "alpha-source-lock/1"},
		"check":  map[string]any{"source_id": getID, "method": "GET", "path": "/widgets", "success_statuses": []any{"200"}},
		"operations": []any{
			map[string]any{"source_id": getID, "state": "materialized", "citation": map[string]any{"document_id": "get", "location": `paths["/widgets"].get`}, "binding": map[string]any{"kind": "direct_read", "id": "list_widgets", "command_path": "widgets list", "command_summary": "List widgets", "output_policy": "json_redacted", "max_response_bytes": 4096, "success_statuses": []any{"200"}, "risk": "low"}},
			map[string]any{"source_id": postID, "state": "materialized", "citation": map[string]any{"document_id": "post", "location": `paths["/widgets"].post`}, "inputs": []any{map[string]any{"source": "body.title", "target": "record.title"}}, "binding": map[string]any{"kind": "write", "id": "create_widget", "success_statuses": []any{"201"}, "request_media": "application/json", "write_kind": "create", "mutation_class": "create", "approval": "destructive", "risk": "high"}},
		},
	}
	if options.MissingBodyBinding {
		plan["operations"].([]any)[1].(map[string]any)["inputs"] = []any{}
	}
	if options.WrongRequestMedia {
		plan["operations"].([]any)[1].(map[string]any)["binding"].(map[string]any)["request_media"] = "application/xml"
	}
	if options.DuplicateAccounting {
		plan["operations"] = append(plan["operations"].([]any), plan["operations"].([]any)[0])
	}
	if options.UnknownMaterializationField {
		plan["unexpected"] = true
	}
	lock := sourceMaterializeV4Lock(t, getRaw, postRaw, plan)
	if options.Legacy {
		lock = sourceImportV3FixtureLock(t, "alpha", []sourceImportV3FixtureDocument{{ID: "get", Path: "/widgets", OperationID: "listWidgets", Artifact: getRaw}})
	}
	if err := os.WriteFile(filepath.Join(sourcesDir, "alpha-operation-source-lock.json"), lock, 0o644); err != nil {
		t.Fatal(err)
	}
	if options.OutputSymlink {
		if err := os.Symlink(filepath.Join(defsRoot, "outside"), filepath.Join(defsRoot, "alpha", "metadata.json")); err != nil {
			t.Fatal(err)
		}
	}
	fetcher := sourceImportFetchFunc(func(_ context.Context, sourceURL string) ([]byte, error) {
		switch sourceURL {
		case "https://fixtures.polymetrics.invalid/get.openapi.json":
			return getRaw, nil
		case "https://fixtures.polymetrics.invalid/post.openapi.json":
			return postRaw, nil
		default:
			return nil, os.ErrNotExist
		}
	})
	return defsRoot, lock, fetcher
}

func sourceMaterializeV4Lock(t *testing.T, getRaw, postRaw []byte, plan map[string]any) []byte {
	t.Helper()
	document := func(id, method, operationID string, raw []byte) map[string]any {
		lockRaw := sourceImportV3FixtureLock(t, "alpha", []sourceImportV3FixtureDocument{{ID: id, Path: "/widgets", Method: method, OperationID: operationID, Artifact: raw}})
		var lock map[string]any
		if err := json.Unmarshal(lockRaw, &lock); err != nil {
			t.Fatal(err)
		}
		return lock["rest"].(map[string]any)["source_documents"].([]any)[0].(map[string]any)
	}
	lock := map[string]any{"schema_version": 4, "connector": "alpha", "rest": map[string]any{"retrieval": "hermetic v4 fixture capture", "openapi": []any{"3.0.3"}, "source_documents": []any{document("get", "GET", "listWidgets", getRaw), document("post", "POST", "createWidget", postRaw)}}, "counts": map[string]any{"rest": 2, "graphql_query": 0, "graphql_mutation": 0, "total": 2}, "materialization": plan}
	raw, err := json.Marshal(lock)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

func sourceMaterializeOwnedBytes(t *testing.T, bundleDir string) []byte {
	t.Helper()
	var out bytes.Buffer
	for _, name := range []string{"metadata.json", "spec.json", "streams.json", "writes.json", "operations.json", "api_surface.json", "cli_surface.json", "docs.md", "missing-foundation.json", filepath.Join("sources", "alpha-operation-descriptor.json")} {
		raw, err := os.ReadFile(filepath.Join(bundleDir, name))
		if err != nil {
			t.Fatal(err)
		}
		out.WriteString(name)
		out.WriteByte(0)
		out.Write(raw)
		out.WriteByte(0)
	}
	return out.Bytes()
}
