package main

import (
	"context"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// This table validates diagnostic IDs only. It has no runtime factory or route.
func generateSourceCapabilities(ctx context.Context, repo string) (string, error) {
	root, err := os.OpenRoot(repo)
	if err != nil {
		return "", err
	}
	defer func() { _ = root.Close() }()
	cache := sourceProofFileCache{ctx: ctx, root: root, limits: sourceProofFileLimits{UniqueBytes: 64 << 20, Files: 1}, files: map[string]*sourceProofFile{}}
	atlas, err := readSourceFoundationAtlas(&cache)
	if err != nil {
		return "", err
	}
	ids := make([]string, 0, len(atlas.entries))
	for id := range atlas.entries {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var b strings.Builder
	b.WriteString("// Code generated by connectorgen gen. DO NOT EDIT.\npackage connectors\n\n")
	fmt.Fprintf(&b, "const sourceCapabilityCatalogSHA256 = %q\n", atlas.pin.SHA256)
	b.WriteString("\n// sourceCapabilityMetadata is a closed diagnostic enum, never an executor registry.\nfunc sourceCapabilityMetadata(id string) (name, status string, known bool) {\nswitch id {\n")
	for _, id := range ids {
		e := atlas.entries[id]
		if e.Summary == "" || (e.Status != "available" && e.Status != "partial" && e.Status != "missing" && e.Status != "planned") {
			return "", fmt.Errorf("source capability %q has invalid name/status", id)
		}
		fmt.Fprintf(&b, "case %q: return %q, %q, true\n", id, e.Summary, e.Status)
	}
	b.WriteString("default: return \"\", \"\", false\n}\n}\n")

	b.WriteString("\n// sourceGapValid checks generated diagnostic demand identity, never dispatch.\nfunc sourceGapValid(v SourceVisibility, o SourceOperationObservation, c SourceCellObservation) bool {\n")
	for _, demand := range sourceFoundationDemandCatalog() {
		fmt.Fprintf(&b, "if o.Source == (SourceOperationKey{Connector:%q, Inventory:%q, ID:%q}) && c.Lane == %q && o.Protocol == %q && o.Method == %q && o.Path == %q && c.Capability.AtlasID != nil && *c.Capability.AtlasID == %q && c.Capability.GapID == %q {\n", demand.Key.Connector, demand.Key.Inventory, demand.Key.ID, "sync_transport", demand.Protocol, demand.Method, demand.Path, demand.AtlasID, demand.Gap)
		fmt.Fprintf(&b, "documentOK := false; for _, d := range v.Documents { if d.Path == %q && d.RetainedFileSHA256 == %q { documentOK = true } }; if !documentOK { return false }\n", demand.SourcePath, demand.SourceSHA256)
		owners := append([]string{demand.AtlasID}, demand.DecisionOwners...)
		fmt.Fprintf(&b, "if len(c.OwnerRefs) != %d { return false }\n", len(owners))
		for _, owner := range owners {
			fmt.Fprintf(&b, "{ found:=0; for _,owner:=range c.OwnerRefs { if owner==%q {found++} };if found!=1{return false} }\n", owner)
		}
		for _, ref := range demand.Citations {
			fmt.Fprintf(&b, "{ found:=false; for _,i:=range c.LaneFacts { if i>=0 && i<len(v.Citations) { r:=v.Citations[i];if r.DocumentID==%q && r.Pointer==%q && r.ValueSHA256==%q {found=true} } };if !found{return false} }\n", ref.DocumentID, ref.Pointer, ref.ValueSHA256)
		}
		b.WriteString("return true\n}\n")
	}
	b.WriteString("return false\n}\n")
	cache.finalize()
	for _, file := range cache.files {
		if file.code != "" {
			return "", fmt.Errorf("source capability input changed: %s", file.code)
		}
	}
	raw, err := format.Source([]byte(b.String()))
	return string(raw), err
}
