package manifeststore

import (
	"container/list"
	"context"
	"errors"
	"fmt"
	"sync"

	"polymetrics.ai/internal/connectors/engine"
	"polymetrics.ai/internal/connectors/manifestidentity"
	"polymetrics.ai/internal/connectors/manifestindex"
)

var (
	ErrBundleOversize         = errors.New("bundle exceeds manifest store byte limit")
	ErrBundleCapacity         = errors.New("manifest store capacity is held")
	ErrBundleIdentityMismatch = errors.New("manifest entry identity does not match index")
)

// Limits bounds retained decoded bundles and distinct in-flight loads by entry count and generated byte charge.
type Limits struct {
	Entries int
	Bytes   int
}

type bundleIdentity struct {
	connector  string
	generation string
	digest     string
}

func identityFor(entry manifestindex.Entry) bundleIdentity {
	return bundleIdentity{connector: entry.Connector, generation: entry.Generation, digest: entry.Digest}
}

func sameIdentity(left, right manifestindex.Entry) bool {
	return identityFor(left) == identityFor(right)
}

// GenerationLease pins one selected generation after its decoded bundle is no
// longer cache-held. A publisher can use the hold to avoid pruning a generation
// still owned by a constructed executor.
type GenerationLease struct {
	entry   manifestindex.Entry
	release func()
	once    sync.Once
}

// Entry returns the exact generation identity held by this lease.
func (l *GenerationLease) Entry() manifestindex.Entry { return cloneManifestEntry(l.entry) }

// Release drops the generation hold. It is idempotent.
func (l *GenerationLease) Release() {
	if l == nil || l.release == nil {
		return
	}
	l.once.Do(l.release)
}

// LoadedBundle is the identity-bearing result of loading one immutable
// execution generation. Bundle.Identity and Identity must agree exactly.
type LoadedBundle struct {
	Bundle   *engine.Bundle
	Identity manifestidentity.Identity
}

// BundleLoader loads one immutable execution bundle selected by an index entry.
type BundleLoader func(context.Context, manifestindex.Entry) (LoadedBundle, error)

// BundleHandle pins one acquired immutable bundle until Release.
type BundleHandle struct {
	bundle  *engine.Bundle
	entry   manifestindex.Entry
	hold    func() *GenerationLease
	release func()
	once    sync.Once
}

// Bundle returns the immutable bundle selected by the entry.
func (h *BundleHandle) Bundle() *engine.Bundle { return h.bundle }

// Entry returns the exact generated identity that selected Bundle.
func (h *BundleHandle) Entry() manifestindex.Entry { return cloneManifestEntry(h.entry) }

// HoldGeneration pins the selected identity after Bundle itself is released.
func (h *BundleHandle) HoldGeneration() *GenerationLease {
	if h == nil || h.hold == nil {
		return nil
	}
	return h.hold()
}

// Release permits a cached bundle to be evicted. It is idempotent.
func (h *BundleHandle) Release() {
	if h == nil || h.release == nil {
		return
	}
	h.once.Do(h.release)
}

type BundleStore struct {
	index  manifestindex.Index
	limits Limits
	loader BundleLoader

	mu              sync.Mutex
	cache           map[bundleIdentity]*bundleCacheEntry
	lru             list.List
	bytes           int
	reserved        int
	reservedEntries int
	flights         map[bundleIdentity]*bundleFlight
	holds           map[bundleIdentity]int
}

type bundleCacheEntry struct {
	bundle *engine.Bundle
	entry  manifestindex.Entry
	bytes  int
	refs   int
	elem   *list.Element
}

type bundleFlight struct {
	ctx     context.Context
	cancel  context.CancelFunc
	done    chan struct{}
	waiters int
	entry   manifestindex.Entry
	bundle  *engine.Bundle
	err     error
}

// NewBundleStore creates a bounded, cancellation-safe store over one immutable index.
func NewBundleStore(index manifestindex.Index, limits Limits, loader BundleLoader) (*BundleStore, error) {
	if limits.Entries <= 0 {
		return nil, fmt.Errorf("manifest store entry limit must be positive")
	}
	if limits.Bytes <= 0 {
		return nil, fmt.Errorf("manifest store byte limit must be positive")
	}
	if loader == nil {
		return nil, fmt.Errorf("manifest bundle loader is required")
	}
	return &BundleStore{
		index:   index,
		limits:  limits,
		loader:  loader,
		cache:   make(map[bundleIdentity]*bundleCacheEntry),
		flights: make(map[bundleIdentity]*bundleFlight),
		holds:   make(map[bundleIdentity]int),
	}, nil
}

// Acquire returns the current indexed bundle for connector.
func (s *BundleStore) Acquire(ctx context.Context, connector string) (*BundleHandle, error) {
	if ctx == nil {
		return nil, fmt.Errorf("manifest acquire context is required")
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	s.mu.Lock()
	entry, ok := s.index.Lookup(connector)
	s.mu.Unlock()
	if !ok {
		return nil, fmt.Errorf("unknown manifest connector %q", connector)
	}
	return s.AcquireEntry(ctx, entry)
}

// AcquireEntry returns a held bundle only when entry has the exact indexed
// connector, generation, and digest identity.
func (s *BundleStore) AcquireEntry(ctx context.Context, entry manifestindex.Entry) (*BundleHandle, error) {
	if ctx == nil {
		return nil, fmt.Errorf("manifest acquire context is required")
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	s.mu.Lock()
	canonical, ok := s.index.Lookup(entry.Connector)
	if !ok {
		s.mu.Unlock()
		return nil, fmt.Errorf("unknown manifest connector %q", entry.Connector)
	}
	if !sameIdentity(canonical, entry) {
		s.mu.Unlock()
		return nil, fmt.Errorf("%w: %q", ErrBundleIdentityMismatch, entry.Connector)
	}
	if canonical.Bytes > s.limits.Bytes {
		s.mu.Unlock()
		return nil, fmt.Errorf("%w: %q", ErrBundleOversize, canonical.Connector)
	}
	key := identityFor(canonical)
	if cached, ok := s.cache[key]; ok {
		cached.refs++
		s.lru.MoveToFront(cached.elem)
		handle := s.handleLocked(key, cached)
		s.mu.Unlock()
		return handle, nil
	}
	if pending, ok := s.flights[key]; ok {
		pending.waiters++
		s.mu.Unlock()
		return s.wait(ctx, key, pending)
	}
	if err := s.reserveLocked(canonical.Bytes); err != nil {
		s.mu.Unlock()
		return nil, err
	}
	loadCtx, cancel := context.WithCancel(context.Background())
	pending := &bundleFlight{ctx: loadCtx, cancel: cancel, done: make(chan struct{}), waiters: 1, entry: canonical}
	s.flights[key] = pending
	s.mu.Unlock()

	go s.load(key, canonical, pending)
	return s.wait(ctx, key, pending)
}

func (s *BundleStore) wait(ctx context.Context, key bundleIdentity, pending *bundleFlight) (*BundleHandle, error) {
	select {
	case <-pending.done:
		if pending.err != nil {
			return nil, pending.err
		}
		s.mu.Lock()
		if cached, ok := s.cache[key]; ok && cached.bundle == pending.bundle {
			cached.refs++
			s.lru.MoveToFront(cached.elem)
			handle := s.handleLocked(key, cached)
			s.mu.Unlock()
			return handle, nil
		}
		bundle := pending.bundle
		entry := pending.entry
		s.mu.Unlock()
		return s.newHandle(key, bundle, entry, nil), nil
	case <-ctx.Done():
		s.releaseWaiter(key, pending)
		return nil, ctx.Err()
	}
}

func (s *BundleStore) reserveLocked(bytes int) error {
	for len(s.cache)+s.reservedEntries >= s.limits.Entries || s.bytes+s.reserved > s.limits.Bytes-bytes {
		oldest := s.oldestUnheldLocked()
		if oldest == nil {
			return ErrBundleCapacity
		}
		key := oldest.Value.(bundleIdentity)
		cached := s.cache[key]
		delete(s.cache, key)
		s.lru.Remove(cached.elem)
		s.bytes -= cached.bytes
	}
	s.reserved += bytes
	s.reservedEntries++
	return nil
}

func (s *BundleStore) oldestUnheldLocked() *list.Element {
	for candidate := s.lru.Back(); candidate != nil; candidate = candidate.Prev() {
		if s.cache[candidate.Value.(bundleIdentity)].refs == 0 {
			return candidate
		}
	}
	return nil
}

func (s *BundleStore) load(key bundleIdentity, entry manifestindex.Entry, pending *bundleFlight) {
	loaded, err := s.loader(pending.ctx, entry)
	bundle := loaded.Bundle
	if err == nil && !loadedIdentityMatches(entry, loaded) {
		err = fmt.Errorf("%w: loaded generation for %q", ErrBundleIdentityMismatch, entry.Connector)
	}

	s.mu.Lock()
	s.reserved -= entry.Bytes
	s.reservedEntries--
	if s.flights[key] == pending {
		delete(s.flights, key)
		if err == nil {
			elem := s.lru.PushFront(key)
			s.cache[key] = &bundleCacheEntry{bundle: bundle, entry: entry, bytes: entry.Bytes, elem: elem}
			s.bytes += entry.Bytes
		}
	}
	pending.bundle = bundle
	pending.err = err
	close(pending.done)
	s.mu.Unlock()
}

func loadedIdentityMatches(entry manifestindex.Entry, loaded LoadedBundle) bool {
	if loaded.Bundle == nil || loaded.Bundle.Name != entry.Connector {
		return false
	}
	want := manifestidentity.Identity{
		Connector:  entry.Connector,
		Generation: entry.Generation,
		Digest:     entry.Digest,
		Bytes:      entry.Bytes,
	}
	return loaded.Identity == want && loaded.Bundle.Identity == want
}

func (s *BundleStore) handleLocked(key bundleIdentity, cached *bundleCacheEntry) *BundleHandle {
	return s.newHandle(key, cached.bundle, cached.entry, func() {
		s.mu.Lock()
		defer s.mu.Unlock()
		if current, ok := s.cache[key]; ok && current == cached && current.refs > 0 {
			current.refs--
		}
	})
}

func (s *BundleStore) newHandle(key bundleIdentity, bundle *engine.Bundle, entry manifestindex.Entry, release func()) *BundleHandle {
	return &BundleHandle{
		bundle: bundle,
		entry:  entry,
		hold: func() *GenerationLease {
			return s.holdGeneration(key, entry)
		},
		release: release,
	}
}

func (s *BundleStore) holdGeneration(key bundleIdentity, entry manifestindex.Entry) *GenerationLease {
	s.mu.Lock()
	s.holds[key]++
	s.mu.Unlock()
	return &GenerationLease{
		entry: entry,
		release: func() {
			s.mu.Lock()
			defer s.mu.Unlock()
			if s.holds[key] > 1 {
				s.holds[key]--
			} else {
				delete(s.holds, key)
			}
		},
	}
}

// GenerationHeld reports whether a selected generation is pinned by a live
// construction after its cache handle has been released.
func (s *BundleStore) GenerationHeld(entry manifestindex.Entry) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.holds[identityFor(entry)] > 0
}

func cloneManifestEntry(entry manifestindex.Entry) manifestindex.Entry {
	if entry.Metadata.Icon != nil {
		icon := *entry.Metadata.Icon
		entry.Metadata.Icon = &icon
	}
	return entry
}

func (s *BundleStore) releaseWaiter(key bundleIdentity, pending *bundleFlight) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.flights[key] != pending {
		return
	}
	pending.waiters--
	if pending.waiters == 0 {
		delete(s.flights, key)
		pending.cancel()
	}
}
