// AUTO-GENERATED by scripts/gen-connector-catalog.mjs - DO NOT EDIT.
// Source: website/data/connectors.generated.json
// Run `npm run gen:catalog` to regenerate.

import catalogData from './connectors.catalog.data.generated.json';
import type { ConnectorCapabilities, ConnectorMeta } from './connectors.types';

export const CONNECTOR_CATALOG = catalogData as ConnectorMeta[];

export const CONNECTOR_CATALOG_COUNT = 553;

export const CONNECTOR_CATEGORY_COUNTS = {"api":548,"queue":1,"database":3,"accounting":1} as Record<string, number>;

export const CONNECTOR_RELEASE_STAGE_COUNTS = {"ga":486,"alpha":39,"beta":28} as Record<string, number>;

export const CONNECTOR_CAPABILITY_COUNTS = {"check":552,"read":553,"write":242,"query":0,"cdc":1,"dynamicSchema":6} as Record<keyof ConnectorCapabilities, number>;

const BY_SLUG: Record<string, ConnectorMeta> = Object.fromEntries(
  CONNECTOR_CATALOG.map((c) => [c.slug, c]),
);

export function connectorBySlug(slug: string): ConnectorMeta | undefined {
  return BY_SLUG[slug];
}
