// AUTO-GENERATED by scripts/gen-connector-catalog.mjs - DO NOT EDIT.
// Source: website/data/connectors.generated.json
// Run `npm run gen:catalog` to regenerate.

import catalogData from './connectors.catalog.data.generated.json';
import type { ConnectorCapabilities, ConnectorMeta } from './connectors.types';

export const CONNECTOR_CATALOG = catalogData as ConnectorMeta[];

export const CONNECTOR_CATALOG_COUNT = 548;

export const CONNECTOR_CATEGORY_COUNTS = {"api":544,"queue":1,"database":2,"accounting":1} as Record<string, number>;

export const CONNECTOR_RELEASE_STAGE_COUNTS = {"ga":486,"alpha":36,"beta":26} as Record<string, number>;

export const CONNECTOR_CAPABILITY_COUNTS = {"check":548,"read":548,"write":224,"query":0,"cdc":0,"dynamicSchema":4} as Record<keyof ConnectorCapabilities, number>;

const BY_SLUG: Record<string, ConnectorMeta> = Object.fromEntries(
  CONNECTOR_CATALOG.map((c) => [c.slug, c]),
);

export function connectorBySlug(slug: string): ConnectorMeta | undefined {
  return BY_SLUG[slug];
}
