package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"polymetrics.ai/internal/connectors"
)

func writeCLIDocs(dir string, registry *connectors.Registry, selected ...string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if len(selected) == 0 {
		topics := make([]string, 0, len(docs))
		for topic := range docs {
			if topic == "" || topic == "pm" {
				continue
			}
			topics = append(topics, topic)
		}
		sort.Strings(topics)
		for _, topic := range topics {
			path := filepath.Join(dir, topic+".md")
			if err := os.WriteFile(path, []byte(cliDocMarkdown(docs[topic])), 0o644); err != nil {
				return err
			}
		}
	}
	return writeConnectorCommandDocs(dir, registry, selected...)
}

func validateCLIDocs(dir string, registry *connectors.Registry, selected ...string) error {
	return validateConnectorCommandDocs(dir, registry, selected...)
}

func cliDocMarkdown(text string) string {
	return "```\n" + text + "\n```\n"
}

func writeConnectorCommandDocs(dir string, registry *connectors.Registry, selected ...string) error {
	names, err := connectorDocNames(registry, selected)
	if err != nil {
		return err
	}
	for _, name := range names {
		connector, ok := registry.Get(name)
		if !ok {
			continue
		}
		provider, ok := connector.(connectors.CommandSurfaceProvider)
		if !ok || provider.CommandSurface() == nil {
			continue
		}
		markdown, err := connectorCommandDocMarkdown(name, provider.CommandSurface())
		if err != nil {
			return err
		}
		path := filepath.Join(dir, name+".md")
		if err := os.WriteFile(path, []byte(markdown), 0o644); err != nil {
			return fmt.Errorf("write connector command doc %s: %w", name, err)
		}
	}
	return nil
}

func validateConnectorCommandDocs(dir string, registry *connectors.Registry, selected ...string) error {
	names, err := connectorDocNames(registry, selected)
	if err != nil {
		return err
	}
	for _, name := range names {
		connector, ok := registry.Get(name)
		if !ok {
			continue
		}
		provider, ok := connector.(connectors.CommandSurfaceProvider)
		if !ok || provider.CommandSurface() == nil {
			continue
		}
		markdown, err := connectorCommandDocMarkdown(name, provider.CommandSurface())
		if err != nil {
			return err
		}
		path := filepath.Join(dir, name+".md")
		if err := validateGeneratedFile(path, markdown, "connector command doc"); err != nil {
			return err
		}
	}
	return nil
}

func connectorCommandDocMarkdown(name string, surface *connectors.CommandSurface) (string, error) {
	var out strings.Builder
	handled, err := tryWriteConnectorSurfaceHelp(name, surface, nil, &out, false)
	if err != nil {
		return "", err
	}
	if !handled {
		return "", fmt.Errorf("connector %s command surface did not render namespace help", name)
	}
	return "# pm " + name + "\n\n```text\n" + strings.TrimRight(out.String(), "\n") + "\n```\n", nil
}

func validateGeneratedFile(path, want, label string) error {
	got, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("missing %s at %s: %w", label, path, err)
	}
	if string(got) != want {
		return fmt.Errorf("%s drift at %s; run pm docs generate", label, path)
	}
	return nil
}

func writeConnectorDocs(dir string, registry *connectors.Registry, selected ...string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create connector docs dir: %w", err)
	}
	global := len(selected) == 0
	if global {
		if err := copyConnectorIconAssets(dir); err != nil {
			return err
		}
		if err := writeConnectorCatalogDocs(filepath.Join(dir, "catalog"), registry.CatalogEntries()); err != nil {
			return err
		}
	}
	names, err := connectorDocNames(registry, selected)
	if err != nil {
		return err
	}
	index := strings.Builder{}
	index.WriteString("# Connector Manuals\n\n")
	index.WriteString("> Auto-generated by `pm docs generate`.\n\n")
	index.WriteString("## Connector Catalog\n\n")
	index.WriteString("- [All connectors](catalog/all-connectors.md): generated catalog from declarative bundles and Tier-3 natives.\n\n")
	index.WriteString("## Runtime Connectors\n\n")
	for _, name := range names {
		connector, ok := registry.Get(name)
		if !ok {
			continue
		}
		if err := connectors.ValidateConnectorGuide(connector); err != nil {
			return err
		}
		connectorDir := filepath.Join(dir, name)
		if err := os.MkdirAll(connectorDir, 0o755); err != nil {
			return fmt.Errorf("create connector docs %s: %w", name, err)
		}
		manual := connectorManualDocMarkdown(name, connector)
		if !global {
			manual = trimGeneratedTrailingWhitespace(manual)
		}
		if err := os.WriteFile(filepath.Join(connectorDir, "MANUAL.md"), []byte(manual), 0o644); err != nil {
			return fmt.Errorf("write connector manual %s: %w", name, err)
		}
		skill := connectors.RenderConnectorSkill(connector)
		if !global {
			skill = trimGeneratedTrailingWhitespace(skill)
		}
		if err := os.WriteFile(filepath.Join(connectorDir, "SKILL.md"), []byte(skill), 0o644); err != nil {
			return fmt.Errorf("write connector skill %s: %w", name, err)
		}
		if global {
			index.WriteString("- [" + name + "](" + name + "/MANUAL.md): " + connector.Metadata().Description + "\n")
		}
	}
	if global {
		if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(index.String()), 0o644); err != nil {
			return fmt.Errorf("write connector docs index: %w", err)
		}
	}
	return nil
}

func validateConnectorDocs(dir string, registry *connectors.Registry, selected ...string) error {
	global := len(selected) == 0
	if global {
		if err := validateConnectorCatalogDocs(filepath.Join(dir, "catalog"), len(registry.CatalogEntries())); err != nil {
			return err
		}
		if err := connectors.ValidateConnectorIcons(dir, registry.CatalogEntries(), registry.List()); err != nil {
			return err
		}
	}
	names, err := connectorDocNames(registry, selected)
	if err != nil {
		return err
	}
	for _, name := range names {
		connector, ok := registry.Get(name)
		if !ok {
			continue
		}
		if err := connectors.ValidateConnectorGuide(connector); err != nil {
			return err
		}
		manualPath := filepath.Join(dir, name, "MANUAL.md")
		if global {
			manual, err := os.ReadFile(manualPath)
			if err != nil {
				return fmt.Errorf("connector %s missing manual at %s: %w", name, manualPath, err)
			}
			for _, required := range []string{"NAME", "SYNOPSIS", "DESCRIPTION", "ICON", "SECURITY", "AGENT WORKFLOW"} {
				if !strings.Contains(string(manual), required) {
					return fmt.Errorf("connector %s manual missing %s", name, required)
				}
			}
			if err := validateConnectorSkillStructure(dir, name); err != nil {
				return err
			}
			continue
		}
		manual := trimGeneratedTrailingWhitespace(connectorManualDocMarkdown(name, connector))
		if err := validateGeneratedFile(manualPath, manual, "connector manual"); err != nil {
			return err
		}
		if err := validateConnectorSkillFile(dir, name, connector); err != nil {
			return err
		}
	}
	return nil
}

func connectorDocNames(registry *connectors.Registry, selected []string) ([]string, error) {
	if len(selected) == 0 {
		names := make([]string, 0, len(registry.List()))
		for _, meta := range registry.List() {
			names = append(names, meta.Name)
		}
		return names, nil
	}
	unique := make(map[string]struct{}, len(selected))
	for _, name := range selected {
		name = strings.TrimSpace(name)
		if name == "" {
			return nil, errors.New("--connector requires a connector name")
		}
		if _, ok := registry.Get(name); !ok {
			return nil, fmt.Errorf("unknown connector %q", name)
		}
		unique[name] = struct{}{}
	}
	names := make([]string, 0, len(unique))
	for name := range unique {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

func connectorManualDocMarkdown(name string, connector connectors.Connector) string {
	return "# pm connectors inspect " + name + "\n\n```text\n" + connectors.RenderConnectorManual(connector) + "\n```\n"
}

func validateConnectorSkillFile(dir, name string, connector connectors.Connector) error {
	skillPath := filepath.Join(dir, name, "SKILL.md")
	return validateGeneratedFile(skillPath, trimGeneratedTrailingWhitespace(connectors.RenderConnectorSkill(connector)), "connector skill")
}

func trimGeneratedTrailingWhitespace(text string) string {
	lines := strings.Split(text, "\n")
	for i := range lines {
		lines[i] = strings.TrimRight(lines[i], " \t")
	}
	return strings.Join(lines, "\n")
}

func validateConnectorSkillStructure(dir, name string) error {
	skillPath := filepath.Join(dir, name, "SKILL.md")
	skill, err := os.ReadFile(skillPath)
	if err != nil {
		return fmt.Errorf("connector %s missing skill at %s: %w", name, skillPath, err)
	}
	for _, required := range []string{"name: pm-" + name, "## Agent Rules"} {
		if !strings.Contains(string(skill), required) {
			return fmt.Errorf("connector %s skill missing %q", name, required)
		}
	}
	return nil
}

func writeConnectorCatalogDocs(dir string, defs []connectors.Definition) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create connector catalog docs dir: %w", err)
	}
	data, err := json.MarshalIndent(defs, "", "  ")
	if err != nil {
		return fmt.Errorf("encode connector catalog: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(filepath.Join(dir, "all-connectors.json"), data, 0o644); err != nil {
		return fmt.Errorf("write connector catalog json: %w", err)
	}
	var b strings.Builder
	b.WriteString("# Connector Catalog\n\n")
	b.WriteString("> Auto-generated by `pm docs generate`. Image references are metadata only; runtime capabilities come from connector bundles and Tier-3 natives.\n\n")
	b.WriteString("| Name | Icon | Display Name | Type | Release | Capabilities | Streams | Writes | Documentation | Connector Metadata |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, def := range defs {
		b.WriteString("| `" + def.Name + "` | " + catalogIconMarkdown(def.Icon) + " | " + markdownCell(def.DisplayName) + " | `" + markdownCell(def.IntegrationType) + "` | " + markdownCell(def.ReleaseStage) + " | " + catalogCapabilitySummary(def.Capabilities) + " | " + fmt.Sprintf("%d", len(def.Streams)) + " | " + fmt.Sprintf("%d", len(def.WriteActions)) + " | " + definitionDocsMarkdown(def) + " | bundle definition |\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "all-connectors.md"), []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write connector catalog markdown: %w", err)
	}
	return nil
}

func validateConnectorCatalogDocs(dir string, wantDefs int) error {
	jsonPath := filepath.Join(dir, "all-connectors.json")
	mdPath := filepath.Join(dir, "all-connectors.md")
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return fmt.Errorf("connector catalog missing json at %s: %w", jsonPath, err)
	}
	var defs []connectors.Definition
	if err := json.Unmarshal(data, &defs); err != nil {
		return fmt.Errorf("decode connector catalog json: %w", err)
	}
	if len(defs) != wantDefs {
		return fmt.Errorf("connector catalog json has %d entries, want %d", len(defs), wantDefs)
	}
	markdown, err := os.ReadFile(mdPath)
	if err != nil {
		return fmt.Errorf("connector catalog missing markdown at %s: %w", mdPath, err)
	}
	for _, required := range []string{"# Connector Catalog", "Icon", "icons/github.svg", "Documentation", "Connector Metadata", "`github`", "`postgres`"} {
		if !strings.Contains(string(markdown), required) {
			return fmt.Errorf("connector catalog markdown missing %q", required)
		}
	}
	return nil
}

func catalogIconMarkdown(icon *connectors.ConnectorIcon) string {
	if icon == nil || icon.Path == "" {
		return "missing"
	}
	return "[`" + markdownCell(icon.Path) + "`](../" + markdownCell(icon.Path) + ")"
}

func catalogCapabilitySummary(caps connectors.Capabilities) string {
	enabled := []string{}
	if caps.Check {
		enabled = append(enabled, "check")
	}
	if caps.Catalog {
		enabled = append(enabled, "catalog")
	}
	if caps.Read {
		enabled = append(enabled, "read")
	}
	if caps.Write {
		enabled = append(enabled, "write")
	}
	if caps.Query {
		enabled = append(enabled, "query")
	}
	if len(enabled) == 0 {
		return "metadata"
	}
	return strings.Join(enabled, ", ")
}

func definitionDocsMarkdown(def connectors.Definition) string {
	if strings.TrimSpace(def.DocsURL) == "" {
		return "manual intervention needed"
	}
	return "[Documentation](" + markdownCell(def.DocsURL) + ")"
}

func connectorDocsProviderReference(values ...string) bool {
	token := connectorDocsProviderReferenceToken()
	for _, value := range values {
		if strings.Contains(strings.ToLower(value), token) {
			return true
		}
	}
	return false
}

func connectorDocsProviderReferenceToken() string {
	return "air" + "byte"
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}

func copyConnectorIconAssets(connectorsDir string) error {
	src, err := connectorIconSourceDir(connectorsDir)
	if err != nil {
		return err
	}
	dst := filepath.Join(connectorsDir, "icons")
	if samePath(src, dst) {
		return nil
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return fmt.Errorf("read connector icon assets from %s: %w", src, err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("create connector icons dir: %w", err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".svg") {
			continue
		}
		if err := copyFile(filepath.Join(src, entry.Name()), filepath.Join(dst, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func connectorIconSourceDir(connectorsDir string) (string, error) {
	root, err := repoRootFromWorkingDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "docs", "connectors", "icons"), nil
}

func repoRootFromWorkingDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from working directory")
		}
		dir = parent
	}
}

func samePath(a, b string) bool {
	absA, errA := filepath.Abs(a)
	absB, errB := filepath.Abs(b)
	if errA != nil || errB != nil {
		return filepath.Clean(a) == filepath.Clean(b)
	}
	return filepath.Clean(absA) == filepath.Clean(absB)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("open connector icon %s: %w", src, err)
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		return fmt.Errorf("create connector icon %s: %w", dst, err)
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return fmt.Errorf("copy connector icon %s: %w", dst, err)
	}
	if err := out.Close(); err != nil {
		return fmt.Errorf("close connector icon %s: %w", dst, err)
	}
	return nil
}
