package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"polymetrics.ai/internal/connectors"
)

func writeConnectorDocs(dir string, registry *connectors.Registry) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create connector docs dir: %w", err)
	}
	if err := writeConnectorCatalogDocs(filepath.Join(dir, "catalog")); err != nil {
		return err
	}
	index := strings.Builder{}
	index.WriteString("# Connector Manuals\n\n")
	index.WriteString("> Auto-generated by `pm docs generate`.\n\n")
	index.WriteString("## Native Implementation Program\n\n")
	index.WriteString("- [Real Native Implementation Plan](REAL_NATIVE_IMPLEMENTATION_PLAN.md): architecture, runtime families, migration phases, and acceptance gates for real native connector ports.\n")
	index.WriteString("- [Airbyte To pm Native Porting Guide](AIRBYTE_TO_PM_PORTING_GUIDE.md): field-by-field translation guide for auth, streams, state, destinations, and conformance.\n")
	index.WriteString("- [Native Implementation Status Policy](NATIVE_IMPLEMENTATION_STATUS_POLICY.md): rules for when a connector can be called fixture-backed, live-ported, or enabled.\n\n")
	index.WriteString("## Enabled Runtime Connectors\n\n")
	for _, meta := range registry.List() {
		connector, ok := registry.Get(meta.Name)
		if !ok {
			continue
		}
		if err := connectors.ValidateConnectorGuide(connector); err != nil {
			return err
		}
		connectorDir := filepath.Join(dir, meta.Name)
		if err := os.MkdirAll(connectorDir, 0o755); err != nil {
			return fmt.Errorf("create connector docs %s: %w", meta.Name, err)
		}
		manual := "# pm connectors inspect " + meta.Name + "\n\n```text\n" + connectors.RenderConnectorManual(connector) + "\n```\n"
		if err := os.WriteFile(filepath.Join(connectorDir, "MANUAL.md"), []byte(manual), 0o644); err != nil {
			return fmt.Errorf("write connector manual %s: %w", meta.Name, err)
		}
		if err := os.WriteFile(filepath.Join(connectorDir, "SKILL.md"), []byte(connectors.RenderConnectorSkill(connector)), 0o644); err != nil {
			return fmt.Errorf("write connector skill %s: %w", meta.Name, err)
		}
		index.WriteString("- [" + meta.Name + "](" + meta.Name + "/MANUAL.md): " + meta.Description + "\n")
	}
	index.WriteString("\n## Catalog Connectors\n\n")
	index.WriteString("- [All connectors](catalog/all-connectors.md): complete generated native-Go-only connector catalog.\n")
	for _, def := range connectors.ConnectorCatalog() {
		if err := connectors.ValidateConnectorDefinitionGuide(def); err != nil {
			return err
		}
		if _, exists := registry.Get(def.Slug); exists {
			index.WriteString("- [" + def.Slug + "](" + def.Slug + "/MANUAL.md): " + def.Name + " (" + string(def.ImplementationStatus) + ")\n")
			continue
		}
		connectorDir := filepath.Join(dir, def.Slug)
		if err := os.MkdirAll(connectorDir, 0o755); err != nil {
			return fmt.Errorf("create connector docs %s: %w", def.Slug, err)
		}
		manual := "# pm connectors inspect " + def.Slug + "\n\n```text\n" + connectors.RenderConnectorDefinitionManual(def) + "\n```\n"
		if err := os.WriteFile(filepath.Join(connectorDir, "MANUAL.md"), []byte(manual), 0o644); err != nil {
			return fmt.Errorf("write connector manual %s: %w", def.Slug, err)
		}
		if err := os.WriteFile(filepath.Join(connectorDir, "SKILL.md"), []byte(connectors.RenderConnectorDefinitionSkill(def)), 0o644); err != nil {
			return fmt.Errorf("write connector skill %s: %w", def.Slug, err)
		}
		index.WriteString("- [" + def.Slug + "](" + def.Slug + "/MANUAL.md): " + def.Name + " (" + string(def.ImplementationStatus) + ")\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(index.String()), 0o644); err != nil {
		return fmt.Errorf("write connector docs index: %w", err)
	}
	return nil
}

func validateConnectorDocs(dir string, registry *connectors.Registry) error {
	if err := validateConnectorCatalogDocs(filepath.Join(dir, "catalog")); err != nil {
		return err
	}
	for _, meta := range registry.List() {
		connector, ok := registry.Get(meta.Name)
		if !ok {
			continue
		}
		if err := connectors.ValidateConnectorGuide(connector); err != nil {
			return err
		}
		manualPath := filepath.Join(dir, meta.Name, "MANUAL.md")
		skillPath := filepath.Join(dir, meta.Name, "SKILL.md")
		manual, err := os.ReadFile(manualPath)
		if err != nil {
			return fmt.Errorf("connector %s missing manual at %s: %w", meta.Name, manualPath, err)
		}
		skill, err := os.ReadFile(skillPath)
		if err != nil {
			return fmt.Errorf("connector %s missing skill at %s: %w", meta.Name, skillPath, err)
		}
		for _, required := range []string{"NAME", "SYNOPSIS", "DESCRIPTION", "SECURITY", "AGENT WORKFLOW"} {
			if !strings.Contains(string(manual), required) {
				return fmt.Errorf("connector %s manual missing %s", meta.Name, required)
			}
		}
		if !strings.Contains(string(skill), "name: pm-"+meta.Name) || !strings.Contains(string(skill), "## Agent Rules") {
			return fmt.Errorf("connector %s skill is incomplete", meta.Name)
		}
	}
	for _, def := range connectors.ConnectorCatalog() {
		if err := connectors.ValidateConnectorDefinitionGuide(def); err != nil {
			return err
		}
		manualPath := filepath.Join(dir, def.Slug, "MANUAL.md")
		skillPath := filepath.Join(dir, def.Slug, "SKILL.md")
		manual, err := os.ReadFile(manualPath)
		if err != nil {
			return fmt.Errorf("connector %s missing manual at %s: %w", def.Slug, manualPath, err)
		}
		skill, err := os.ReadFile(skillPath)
		if err != nil {
			return fmt.Errorf("connector %s missing skill at %s: %w", def.Slug, skillPath, err)
		}
		for _, required := range []string{"NAME", "SYNOPSIS", "DESCRIPTION", "IMPLEMENTATION STATUS", "RUNTIME CAPABILITIES", "NATIVE PORT PLAN", "SECURITY", "AGENT WORKFLOW"} {
			if !strings.Contains(string(manual), required) {
				return fmt.Errorf("connector %s manual missing %s", def.Slug, required)
			}
		}
		if !strings.Contains(string(skill), "name: pm-"+def.Slug) || !strings.Contains(string(skill), "## Agent Rules") {
			return fmt.Errorf("connector %s skill is incomplete", def.Slug)
		}
	}
	return nil
}

func writeConnectorCatalogDocs(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create connector catalog docs dir: %w", err)
	}
	defs := connectors.ConnectorCatalog()
	data, err := json.MarshalIndent(defs, "", "  ")
	if err != nil {
		return fmt.Errorf("encode connector catalog: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(filepath.Join(dir, "all-connectors.json"), data, 0o644); err != nil {
		return fmt.Errorf("write connector catalog json: %w", err)
	}
	var b strings.Builder
	b.WriteString("# Connector Catalog\n\n")
	b.WriteString("> Auto-generated by `pm docs generate`. Upstream image references are metadata only; pm enables runtime only through native Go implementations.\n\n")
	b.WriteString("| Type | Slug | Name | Stage | Support | Runtime | Status | Family | Capabilities | Official Application Documentation | Airbyte Connector Documentation |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, def := range defs {
		plan := connectors.NativePortPlanForDefinition(def)
		b.WriteString("| " + string(def.Type) + " | `" + def.Slug + "` | " + markdownCell(def.Name) + " | " + def.ReleaseStage + " | " + def.SupportLevel + " | `" + string(def.RuntimeKind) + "` | `" + string(def.ImplementationStatus) + "` | `" + string(plan.Family) + "` | " + catalogCapabilitySummary(def.RuntimeCapabilities) + " | " + officialApplicationDocsMarkdown(def.OfficialApplicationDocs) + " | [Airbyte docs](" + def.DocumentationURL + ") |\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "all-connectors.md"), []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write connector catalog markdown: %w", err)
	}
	return nil
}

func validateConnectorCatalogDocs(dir string) error {
	jsonPath := filepath.Join(dir, "all-connectors.json")
	mdPath := filepath.Join(dir, "all-connectors.md")
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return fmt.Errorf("connector catalog missing json at %s: %w", jsonPath, err)
	}
	var defs []connectors.ConnectorDefinition
	if err := json.Unmarshal(data, &defs); err != nil {
		return fmt.Errorf("decode connector catalog json: %w", err)
	}
	if len(defs) != len(connectors.ConnectorCatalog()) {
		return fmt.Errorf("connector catalog json has %d entries, want %d", len(defs), len(connectors.ConnectorCatalog()))
	}
	markdown, err := os.ReadFile(mdPath)
	if err != nil {
		return fmt.Errorf("connector catalog missing markdown at %s: %w", mdPath, err)
	}
	for _, required := range []string{"# Connector Catalog", "Official Application Documentation", "Airbyte Connector Documentation", "source-github", "destination-postgres", "enabled"} {
		if !strings.Contains(string(markdown), required) {
			return fmt.Errorf("connector catalog markdown missing %q", required)
		}
	}
	return nil
}

func catalogCapabilitySummary(caps connectors.RuntimeCapabilities) string {
	enabled := []string{}
	if caps.Check {
		enabled = append(enabled, "check")
	}
	if caps.Catalog {
		enabled = append(enabled, "catalog")
	}
	if caps.Read {
		enabled = append(enabled, "read")
	}
	if caps.Write {
		enabled = append(enabled, "write")
	}
	if caps.Query {
		enabled = append(enabled, "query")
	}
	if caps.ETL {
		enabled = append(enabled, "etl")
	}
	if caps.ReverseETL {
		enabled = append(enabled, "reverse_etl")
	}
	if len(enabled) == 0 {
		return "metadata"
	}
	return strings.Join(enabled, ", ")
}

func officialApplicationDocsMarkdown(docs []connectors.DocumentationLink) string {
	if len(docs) == 0 {
		return "not listed in registry"
	}
	parts := make([]string, 0, len(docs))
	for _, doc := range docs {
		label := markdownCell(doc.Title)
		if label == "" {
			label = markdownCell(doc.Type)
		}
		if label == "" {
			label = "Official documentation"
		}
		if doc.Type != "" {
			label += " (" + markdownCell(doc.Type) + ")"
		}
		parts = append(parts, "["+label+"]("+doc.URL+")")
	}
	return strings.Join(parts, "<br>")
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}
