// Code generated by connectorgen gen. DO NOT EDIT.
//
// Package nativeset blank-imports every internal/connectors/native/<name>
// Tier-3 component package so any package-level side effects (e.g. a
// future documented registration) run in the built binary. In wave0 no
// native package registers itself (see API-CONTRACT.md §6); this file is
// pure wiring, regenerated deterministically as packages are added.
// It is regenerated deterministically by `go run ./cmd/connectorgen gen`.
package nativeset

import (
	_ "polymetrics.ai/internal/connectors/native/alpha-vantage"
	_ "polymetrics.ai/internal/connectors/native/amazon-sqs"
	_ "polymetrics.ai/internal/connectors/native/apify-dataset"
	_ "polymetrics.ai/internal/connectors/native/ashby"
	_ "polymetrics.ai/internal/connectors/native/aws-cloudtrail"
	_ "polymetrics.ai/internal/connectors/native/babelforce"
	_ "polymetrics.ai/internal/connectors/native/basecamp"
	_ "polymetrics.ai/internal/connectors/native/bing-ads"
	_ "polymetrics.ai/internal/connectors/native/bunny-inc"
	_ "polymetrics.ai/internal/connectors/native/canny"
	_ "polymetrics.ai/internal/connectors/native/copper"
	_ "polymetrics.ai/internal/connectors/native/dixa"
	_ "polymetrics.ai/internal/connectors/native/dynamodb"
	_ "polymetrics.ai/internal/connectors/native/faker"
	_ "polymetrics.ai/internal/connectors/native/fastbill"
	_ "polymetrics.ai/internal/connectors/native/feishu"
	_ "polymetrics.ai/internal/connectors/native/free-agent-connector"
	_ "polymetrics.ai/internal/connectors/native/freightview"
	_ "polymetrics.ai/internal/connectors/native/google-analytics-data-api"
	_ "polymetrics.ai/internal/connectors/native/google-calendar"
	_ "polymetrics.ai/internal/connectors/native/google-classroom"
	_ "polymetrics.ai/internal/connectors/native/google-pagespeed-insights"
	_ "polymetrics.ai/internal/connectors/native/less-annoying-crm"
	_ "polymetrics.ai/internal/connectors/native/lokalise"
	_ "polymetrics.ai/internal/connectors/native/mendeley"
	_ "polymetrics.ai/internal/connectors/native/mercado-ads"
	_ "polymetrics.ai/internal/connectors/native/metabase"
	_ "polymetrics.ai/internal/connectors/native/mode"
	_ "polymetrics.ai/internal/connectors/native/my-hours"
	_ "polymetrics.ai/internal/connectors/native/pocket"
	_ "polymetrics.ai/internal/connectors/native/postgres"
	_ "polymetrics.ai/internal/connectors/native/prestashop"
	_ "polymetrics.ai/internal/connectors/native/rootly"
	_ "polymetrics.ai/internal/connectors/native/safetyculture"
	_ "polymetrics.ai/internal/connectors/native/tally-prime"
	_ "polymetrics.ai/internal/connectors/native/yahoo-finance-price"
)
