// Code generated by connectorgen gen. DO NOT EDIT.
//
// Package nativeset blank-imports every internal/connectors/native/<name>
// Tier-3 component package so any package-level side effects (e.g. a
// future documented registration) run in the built binary. In wave0 no
// native package registers itself (see API-CONTRACT.md §6); this file is
// pure wiring, regenerated deterministically as packages are added.
// It is regenerated deterministically by `go run ./cmd/connectorgen gen`.
package nativeset

import (
	_ "polymetrics.ai/internal/connectors/native/amazon-sqs"
	_ "polymetrics.ai/internal/connectors/native/bing-ads"
	_ "polymetrics.ai/internal/connectors/native/dynamodb"
	_ "polymetrics.ai/internal/connectors/native/faker"
	_ "polymetrics.ai/internal/connectors/native/postgres"
	_ "polymetrics.ai/internal/connectors/native/tally-prime"
)
