apiVersion: v1
kind: Service
metadata:
  name: polymetrics-website
  namespace: polymetrics-website
spec:
  selector:
    app: polymetrics-website
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
