// Code generated by connectorgen gen. DO NOT EDIT.
package connectors

const sourceCapabilityCatalogSHA256 = "95d45e22f43b13b9ff1ac8d93c63deac84a4e1c061a5afe13127be2f86c32bf5"

// sourceCapabilityMetadata is a closed diagnostic enum, never an executor registry.
func sourceCapabilityMetadata(id string) (name, status string, known bool) {
	switch id {
	case "authoring.source-lock-vnext.v1":
		return "Strictly validates immutable schema-4 source locks, builds a typed canonical source graph, semantically admits effective source-to-runtime schema joins and complete closed executor/extension selection, deterministically renders execution JSON, then publishes a connector-local closed generation through operation-lifetime no-follow descriptor confinement, connector-directory inode locking, recomputed content addresses, retained terminal control authority, append-only successor repair, private-read revalidation, descriptor-relative no-replace capture, create-only selection, and lease-safe pruning. Its adjacent read-only source-lanes command accounts for independently anchored retained provider operations and seven lane cells without supplying runtime authority.", "available", true
	case "definitions.bundle-loader.v1":
		return "Indexes safe metadata and closed executor/extension identities from embedded execution JSON without decoding bundles, then lazily loads one selected bundle through explicit factories and sealed native compatibility adapters.", "available", true
	case "orchestration.flow-schedule.v1":
		return "Parses and validates persisted flow DAGs, runs saved ETL, query, and authorized action steps with durable checkpoints and receipts, and schedules named flows through non-overlapping fire leases without carrying authorization material.", "available", true
	case "runtime.array-zip-projection.v1":
		return "Zips source-declared equal-length JSON arrays into one emitted record per index with source-declared scalar fields copied onto every row.", "available", true
	case "runtime.cartesian-config-fanout.v1":
		return "Expands a source-declared PageSpeed-style HTTPS URL list and mobile or desktop strategy list into a bounded deterministic Cartesian sequence of GET reads with fixed repeated category query parameters.", "available", true
	case "runtime.date-window-fanout.v1":
		return "Schedules source-declared contiguous UTC date windows into fixed query parameters before the existing ETL reader runs each window.", "available", true
	case "runtime.declared-aws-sigv4.v1":
		return "Applies declaration-bound AWS Signature Version 4 authentication only for fixed CloudTrail us-east-1 requests.", "available", true
	case "runtime.declared-password-token.v1":
		return "Authenticates a declared fixed HTTPS JSON email/password token route, extracts only its top-level accessToken, and applies that bearer token for the lifetime of the runtime without refresh or replay.", "available", true
	case "runtime.declared-response-error.v1":
		return "Rejects a source-declared JSON error object or false success envelope before record extraction and emits a typed declared-response error.", "available", true
	case "runtime.declared-session.v1":
		return "Exchanges declared username and password fields through one fixed session route, extracts the top-level session id, and applies it only as X-Metabase-Session for the lifetime of one runtime.", "available", true
	case "runtime.direct-execution.v1":
		return "Executes definition-bound direct reads, direct writes, binary downloads, and binary uploads through common preflight, request encoding, response handling, preview, approval, and command-binding paths. Its declarative base check can preserve an explicit exact allowed 2xx status set and an explicit response-byte cap through the existing requester policy.", "available", true
	case "runtime.offset-count-pagination.v1":
		return "Advances a source-declared zero-based provider window encoded as one combined offset,count query value until a short page ends the stream.", "available", true
	case "runtime.per-stream-headers.v1":
		return "Applies a source-declared static vendor Accept media type to one ETL stream, deterministically replacing any same-name global header before the existing authenticated requester sends provider I/O.", "available", true
	case "runtime.provider-extension-seams.v1":
		return "Provides bounded hook, native-connector, and definition-factory seams for provider-specific authentication, request, record, protocol, and transport behavior without cloning the generic engines. Includes a definition-selected single_attempt destination seam: one declaration-bound request per record, automatic retries disabled, bounded response capture, and no provider replay or generic writer.", "available", true
	case "runtime.response-header-projection.v1":
		return "Projects source-declared response header names onto equal-length positional value arrays within extracted JSON rows before schema projection and record emission.", "available", true
	case "runtime.tenant-origin.v1":
		return "Resolves one source-declared connection-level tenant origin with an optional fixed API path before constructing the existing declarative HTTP runtime.", "available", true
	case "transport.sync-contract.v1":
		return "Defines the closed sync-mode, checkpoint, tombstone, delivery, and executor-reference contracts and orchestrates definition-selected sources through a durable warehouse stage into definition-selected destinations. single_attempt is a constrained full_append/append delivery class: declaration-bound input fields, one request per record, automatic retries disabled, response-captured durable acknowledgement, and no automatic replay; retry_safe remains a separate keyed/read-back class.", "available", true
	case "warehouse.reverse-etl.v1":
		return "Reads pinned DuckDB warehouse rows, maps them into typed destination actions, persists a payload-bound plan and preview, consumes approval atomically, and dispatches bounded connector writes with result accounting.", "available", true
	case "warehouse.stage-etl.v1":
		return "Stages connection-owned source work durably, materializes WAL records into Parquet-backed DuckDB tables under declared apply strategies, reads back destination receipts, and executes saved ETL through the local warehouse boundary. Full-snapshot materialization does not require a provider row cursor; incremental and history strategies retain their closed durable checkpoint and row-cursor requirements.", "available", true
	default:
		return "", "", false
	}
}

// sourceGapValid checks generated diagnostic demand identity, never dispatch.
func sourceGapValid(v SourceVisibility, o SourceOperationObservation, c SourceCellObservation) bool {
	if o.Source == (SourceOperationKey{Connector: "vercel", Inventory: "primary", ID: "vercel.rest.createWebhook"}) && c.Lane == "sync_transport" && o.Protocol == "rest" && o.Method == "POST" && o.Path == "/v1/webhooks" && c.Capability.AtlasID != nil && *c.Capability.AtlasID == "transport.sync-contract.v1" && c.Capability.GapID == "cli-webhook-event-surface-foundation-r1" {
		documentOK := false
		for _, d := range v.Documents {
			if d.Path == "internal/connectors/defs/vercel/sources/vercel-operation-source-lock.json" && d.RetainedFileSHA256 == "2eb0130c9357c90cf74e6b47da48eac3768fec3ae3de9b15890b24a2d3f10f4e" {
				documentOK = true
			}
		}
		if !documentOK {
			return false
		}
		if len(c.OwnerRefs) != 3 {
			return false
		}
		{
			found := 0
			for _, owner := range c.OwnerRefs {
				if owner == "transport.sync-contract.v1" {
					found++
				}
			}
			if found != 1 {
				return false
			}
		}
		{
			found := 0
			for _, owner := range c.OwnerRefs {
				if owner == "cli-batch1-vercel-inbound-sync-decision-r1" {
					found++
				}
			}
			if found != 1 {
				return false
			}
		}
		{
			found := 0
			for _, owner := range c.OwnerRefs {
				if owner == "cli-plan-webhook-receiver-foundation-r1-decision-webhook-exposure-product-boundary" {
					found++
				}
			}
			if found != 1 {
				return false
			}
		}
		{
			found := false
			for _, i := range c.LaneFacts {
				if i >= 0 && i < len(v.Citations) {
					r := v.Citations[i]
					if r.DocumentID == "vercel:primary" && r.Pointer == "/rest/operations/381/source_operation/summary" && r.ValueSHA256 == "de9630dadd47a37e30684147218c08bddde88fe71a287c7f9f16e00c0aae690f" {
						found = true
					}
				}
			}
			if !found {
				return false
			}
		}
		{
			found := false
			for _, i := range c.LaneFacts {
				if i >= 0 && i < len(v.Citations) {
					r := v.Citations[i]
					if r.DocumentID == "vercel:primary" && r.Pointer == "/rest/operations/381/source_operation/requestBody/required" && r.ValueSHA256 == "b5bea41b6c623f7c09f1bf24dcae58ebab3c0cdd90ad966bc43a45b44867e12b" {
						found = true
					}
				}
			}
			if !found {
				return false
			}
		}
		{
			found := false
			for _, i := range c.LaneFacts {
				if i >= 0 && i < len(v.Citations) {
					r := v.Citations[i]
					if r.DocumentID == "vercel:primary" && r.Pointer == "/rest/operations/381/source_operation/requestBody/content/application~1json/schema/required" && r.ValueSHA256 == "67f049164296f2dc1f1d5c6b5d027464216365b43d74d1fb4780cbc16e13d296" {
						found = true
					}
				}
			}
			if !found {
				return false
			}
		}
		{
			found := false
			for _, i := range c.LaneFacts {
				if i >= 0 && i < len(v.Citations) {
					r := v.Citations[i]
					if r.DocumentID == "vercel:primary" && r.Pointer == "/rest/operations/381/source_operation/requestBody/content/application~1json/schema/properties/url" && r.ValueSHA256 == "7ce701965cb4f5b9b777d0ed12ea7b0a7bb84a44d6982af853efa47ddb6e2741" {
						found = true
					}
				}
			}
			if !found {
				return false
			}
		}
		{
			found := false
			for _, i := range c.LaneFacts {
				if i >= 0 && i < len(v.Citations) {
					r := v.Citations[i]
					if r.DocumentID == "vercel:primary" && r.Pointer == "/rest/operations/381/source_operation/requestBody/content/application~1json/schema/properties/events" && r.ValueSHA256 == "f24ea042467e970d3e04e8f586a44a96d36d8b320889bb1dc97ac1ab9efa9959" {
						found = true
					}
				}
			}
			if !found {
				return false
			}
		}
		return true
	}
	return false
}
