package agentcontract

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

const certificationFlowKindCatalogPath = "internal/certificationcatalog/flow_gen.go"

func CheckCertificationFlowKindCatalog(root string, contract *Contract) (returnErr error) {
	expected, err := renderCertificationFlowKindCatalog(root, contract)
	if err != nil {
		return err
	}
	catalogRoot, err := os.OpenRoot(root)
	if err != nil {
		return fmt.Errorf("open certification flow-kind catalog root: %w", err)
	}
	defer func() {
		if err := catalogRoot.Close(); err != nil && returnErr == nil {
			returnErr = fmt.Errorf("close certification flow-kind catalog root: %w", err)
		}
	}()
	path, err := projectionPath(certificationFlowKindCatalogPath)
	if err != nil {
		return err
	}
	if err := validateProjectionReadPath(catalogRoot, path, true); err != nil {
		return fmt.Errorf("read generated certification flow-kind catalog: %w", err)
	}
	actual, err := catalogRoot.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated certification flow-kind catalog: %w", err)
	}
	if !bytes.Equal(actual, expected) {
		return fmt.Errorf("generated certification flow-kind catalog diverges from flow matrix; run go run ./cmd/agentcontractgen sync")
	}
	return nil
}

func SyncCertificationFlowKindCatalog(root string, contract *Contract) (updated int, returnErr error) {
	expected, err := renderCertificationFlowKindCatalog(root, contract)
	if err != nil {
		return 0, err
	}
	catalogRoot, err := os.OpenRoot(root)
	if err != nil {
		return 0, fmt.Errorf("open certification flow-kind catalog root: %w", err)
	}
	defer func() {
		if err := catalogRoot.Close(); err != nil && returnErr == nil {
			returnErr = fmt.Errorf("close certification flow-kind catalog root: %w", err)
		}
	}()
	path, err := projectionPath(certificationFlowKindCatalogPath)
	if err != nil {
		return 0, err
	}
	if _, err := catalogRoot.Lstat(path); err == nil {
		if err := validateProjectionReadPath(catalogRoot, path, true); err != nil {
			return 0, fmt.Errorf("read generated certification flow-kind catalog: %w", err)
		}
		actual, err := catalogRoot.ReadFile(path)
		if err != nil {
			return 0, fmt.Errorf("read generated certification flow-kind catalog: %w", err)
		}
		if bytes.Equal(actual, expected) {
			return 0, nil
		}
		info, err := catalogRoot.Stat(path)
		if err != nil {
			return 0, fmt.Errorf("stat generated certification flow-kind catalog: %w", err)
		}
		if err := writeAtomic(catalogRoot, path, expected, info.Mode().Perm()); err != nil {
			return 0, fmt.Errorf("write generated certification flow-kind catalog: %w", err)
		}
		return 1, nil
	} else if !os.IsNotExist(err) {
		return 0, fmt.Errorf("inspect generated certification flow-kind catalog: %w", err)
	}
	if err := ensureProjectionDirectory(catalogRoot, filepath.Dir(path)); err != nil {
		return 0, fmt.Errorf("create generated certification flow-kind catalog directory: %w", err)
	}
	if err := writeAtomic(catalogRoot, path, expected, 0o644); err != nil {
		return 0, fmt.Errorf("write generated certification flow-kind catalog: %w", err)
	}
	return 1, nil
}

func renderCertificationFlowKindCatalog(root string, contract *Contract) ([]byte, error) {
	kinds, err := certificationFlowKindsForCatalog(root, contract)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by agentcontractgen; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package certificationcatalog")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "func init() {")
	fmt.Fprintln(&output, "\tregisterGeneratedFlowKinds([]FlowKind{")
	for _, kind := range kinds {
		fmt.Fprintf(&output, "\t\t{ID: %q, SourceRole: %q, DestinationRole: %q},\n", kind.ID, kind.SourceRole, kind.DestinationRole)
	}
	fmt.Fprintln(&output, "\t})")
	fmt.Fprintln(&output, "}")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated certification flow-kind catalog: %w", err)
	}
	return formatted, nil
}

func certificationFlowKindsForCatalog(root string, contract *Contract) ([]certificationFlowKind, error) {
	if contract == nil {
		return nil, fmt.Errorf("canonical delivery contract is required")
	}
	if err := contract.Validate(); err != nil {
		return nil, err
	}
	gate := contract.CertificationGate
	var matrix certificationFlowMatrix
	if gate.Inputs.CertificationShards != "" {
		status, err := loadStatusArtifact(root, gate)
		if err != nil {
			return nil, fmt.Errorf("load producer certification status: %w", err)
		}
		if err := validateStatusArtifact(status, gate); err != nil {
			return nil, fmt.Errorf("validate producer certification status: %w", err)
		}
		_, matrix, err = loadCertificationShardMatrices(root, gate, status)
		if err != nil {
			return nil, fmt.Errorf("load producer certification shards: %w", err)
		}
	} else {
		var err error
		matrix, err = loadFlowMatrix(root, gate)
		if err != nil {
			return nil, fmt.Errorf("load producer flow matrix: %w", err)
		}
	}
	if matrix.SchemaVersion != gate.InputSchemaVersion || matrix.GeneratedCommand != gate.GeneratedCommand || matrix.Mediator != localParquetWarehouse {
		return nil, fmt.Errorf("producer flow matrix has an unsupported schema, command, or mediator")
	}
	if err := validateUniqueIDs("producer flow kind", matrix.FlowKinds, func(kind certificationFlowKind) string { return kind.ID }); err != nil {
		return nil, err
	}
	for _, kind := range matrix.FlowKinds {
		if !safeCertificationID(kind.SourceRole) || !safeCertificationID(kind.DestinationRole) {
			return nil, fmt.Errorf("producer flow kind %q has an unsafe role", kind.ID)
		}
	}
	return matrix.FlowKinds, nil
}
