package boundary

import "testing"

// ownershipCorpusCase encodes real changed-path sets from the eight merge
// commits audited in
// data/cli-first-eight-connector-guardrail-audit-r1/report.md, so the
// target-aware ownership validator's calibration cannot silently regress.
//
// Xero (#3537, 2685c3712a96) and Asana (#3538, fc07dc830342) were audit-
// certified compliant and must keep passing with zero findings. The other
// six merged shared-runtime, unrelated-connector, or unrelated-generated
// changes while the guard in place at the time stayed green, and must keep
// failing: HubSpot (#3529, 41a00398a88d), Stripe (#3530, 86d510927a05),
// Bitbucket (#3531, bfe785464d04), Zendesk Support (#3532, e99d6f119381),
// Google Ads (#3535, 5d61794f76c4), Freshchat (#3536, b053dc4a3ad7).
//
// wantScopedFindings is the finding count with an explicit scope file
// declaring the PR's target connector (how a labeled PR runs the gate).
// wantAutoFindings is the finding count with no scope file at all, so the
// target is inferred purely from changed connector-owned paths (how an
// unlabeled PR runs the gate). Zendesk Support and Google Ads differ
// between the two: their diffs also touch other connectors' paths
// (unrelated generated docs, an unrelated defs/gong/cli_surface.json edit),
// so omitting the scope file collapses per-path findings into a single
// "multiple connector targets inferred" finding instead of the richer
// per-path breakdown — still a rejection, proving label/scope omission
// cannot skip enforcement.
type ownershipCorpusCase struct {
	name               string
	mergeCommit        string
	connector          string
	scopeFile          string
	wantScopedFindings int
	wantAutoFindings   int
	changedPaths       []string
}

var ownershipCorpusCases = []ownershipCorpusCase{
	{
		name:               "hubspot",
		mergeCommit:        "41a00398a88db809b4e799a59fea381ace5cc06e",
		connector:          "hubspot",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/hubspot.scope.json",
		wantScopedFindings: 20,
		wantAutoFindings:   20,
		changedPaths: []string{
			".agents/connector-migration/next-batches.md",
			".planning/phases/issue-132-hubspot-parity-wave01-r1/PLAN.md",
			".planning/phases/issue-132-hubspot-parity-wave01-r1/TDD-LEDGER.md",
			".planning/phases/issue-132-hubspot-parity-wave01-r1/VERIFICATION.md",
			".planning/phases/issue-132-hubspot-parity-wave01-r1/traces/gsd-plan-phase-132.prompt.md",
			".planning/phases/issue-132-hubspot-parity-wave01-r1/traces/gsd-quick-full.prompt.md",
			"docs/GUIDE.md",
			"docs/cli/connectors.md",
			"docs/connectors/README.md",
			"docs/connectors/UNPORTED.md",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/catalog/all-connectors.md",
			"docs/connectors/hubspot/MANUAL.md",
			"docs/connectors/hubspot/SKILL.md",
			"internal/cli/agent_image_cli.go",
			"internal/cli/agentmode_query_cli_test.go",
			"internal/cli/catalog_cli_test.go",
			"internal/cli/certify_cli.go",
			"internal/cli/cli.go",
			"internal/cli/connector_docs.go",
			"internal/cli/docs.go",
			"internal/cli/errors.go",
			"internal/cli/extract_cli.go",
			"internal/cli/flow_cli.go",
			"internal/cli/rlm_cli.go",
			"internal/cli/rlm_cli_test.go",
			"internal/cli/runtime_helpers.go",
			"internal/cli/schedule.go",
			"internal/cli/skills.go",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/cli/version.go",
			"internal/cli/worker_cli.go",
			"internal/connectors/bundleregistry/registry_test.go",
			"internal/connectors/defs/hubspot/api_surface.json",
			"internal/connectors/defs/hubspot/cli_surface.json",
			"internal/connectors/defs/hubspot/docs.md",
			"internal/connectors/defs/hubspot/metadata.json",
			"internal/connectors/defs/hubspot/operations.json",
			"internal/connectors/defs/hubspot/spec.json",
			"internal/connectors/defs/hubspot/streams.json",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
			"website/lib/connectors.catalog.generated.ts",
			"website/lib/connectors.generated.ts",
		},
	},
	{
		name:               "stripe",
		mergeCommit:        "86d510927a05aa56b184bf5a8778b5444c69b9b1",
		connector:          "stripe",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/stripe.scope.json",
		wantScopedFindings: 5,
		wantAutoFindings:   5,
		changedPaths: []string{
			".planning/phases/stripe-parity-3005/PLAN.md",
			".planning/phases/stripe-parity-3005/RUN-STATE.json",
			".planning/phases/stripe-parity-3005/SUMMARY.md",
			".planning/phases/stripe-parity-3005/TDD-LEDGER.md",
			".planning/phases/stripe-parity-3005/VERIFICATION.md",
			"docs/GUIDE.md",
			"docs/architecture/connector-architecture-v2-design.md",
			"docs/connectors/README.md",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/catalog/all-connectors.md",
			"docs/connectors/stripe/MANUAL.md",
			"docs/connectors/stripe/SKILL.md",
			"docs/migration/conventions.md",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/defs/stripe/api_surface.json",
			"internal/connectors/defs/stripe/cli_surface.json",
			"internal/connectors/defs/stripe/docs.md",
			"internal/connectors/defs/stripe/fixtures/writes/delete_customer.json",
			"internal/connectors/defs/stripe/metadata.json",
			"internal/connectors/defs/stripe/writes.json",
			"internal/connectors/engine/write.go",
			"internal/connectors/engine/write_test.go",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
		},
	},
	{
		name:               "bitbucket",
		mergeCommit:        "bfe785464d04fd73dba0c4a70f36e23dd84da3d0",
		connector:          "bitbucket",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/bitbucket.scope.json",
		wantScopedFindings: 15,
		wantAutoFindings:   15,
		changedPaths: []string{
			".planning/phases/issue-79-bitbucket-parity/TDD-LEDGER.md",
			"docs/architecture/connector-architecture-v2-design.md",
			"docs/cli/connectors.md",
			"docs/cli/reverse.md",
			"docs/connectors/README.md",
			"docs/connectors/bitbucket/MANUAL.md",
			"docs/connectors/bitbucket/SKILL.md",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/catalog/all-connectors.md",
			"docs/migration/conventions.md",
			"internal/app/app.go",
			"internal/app/app_test.go",
			"internal/app/types.go",
			"internal/app/util.go",
			"internal/cli/catalog_cli_test.go",
			"internal/cli/cli.go",
			"internal/cli/docs.go",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/bundleregistry/registry_test.go",
			"internal/connectors/defs/bitbucket/GSD-ISSUE-79.md",
			"internal/connectors/defs/bitbucket/api_surface.json",
			"internal/connectors/defs/bitbucket/certification.json",
			"internal/connectors/defs/bitbucket/cli_surface.json",
			"internal/connectors/defs/bitbucket/docs.md",
			"internal/connectors/defs/bitbucket/fixtures/check.json",
			"internal/connectors/defs/bitbucket/fixtures/streams/repositories/page_1.json",
			"internal/connectors/defs/bitbucket/fixtures/streams/repositories/page_2.json",
			"internal/connectors/defs/bitbucket/fixtures/writes/create_repositories_workspace_repo_slug.json",
			"internal/connectors/defs/bitbucket/metadata.json",
			"internal/connectors/defs/bitbucket/operations.json",
			"internal/connectors/defs/bitbucket/schemas/hook_events.json",
			"internal/connectors/defs/bitbucket/schemas/hook_events_subject_type.json",
			"internal/connectors/defs/bitbucket/schemas/repositories.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_branch_restrictions.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_branch_restrictions_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_branching_model.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_branching_model_settings.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_comments.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_comments_comment_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_properties_app_key_property_name.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_pullrequests.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_reports.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_reports_reportid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_reports_reportid_annotations.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_reports_reportid_annotations_annotationid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_statuses.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commit_commit_statuses_build_key.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commits.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_commits_revision.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_components.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_components_component_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_default_reviewers.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_default_reviewers_target_username.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_deploy_keys.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_deploy_keys_key_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_deployments.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_deployments_config_environments_environment_uuid_variables.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_deployments_deployment_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_diffstat_spec.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_effective_branching_model.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_effective_default_reviewers.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_environments.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_environments_environment_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_file_conflicts_spec.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_filehistory_commit_path.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_forks.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_hooks.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_hooks_uid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_import.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_issue_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_issue_id_attachments.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_issue_id_changes.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_issue_id_changes_change_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_issue_id_comments.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_issues_issue_id_comments_comment_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_merge_base_revspec.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_milestones.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_milestones_milestone_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_override_settings.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_permissions_config_groups.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_permissions_config_groups_group_slug.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_permissions_config_users.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_permissions_config_users_selected_user_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_caches.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_caches_cache_uuid_content_uri.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_runners.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_runners_runner_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_schedules.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_schedules_schedule_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_schedules_schedule_uuid_executions.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_ssh_key_pair.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_ssh_known_hosts.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_ssh_known_hosts_known_host_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_variables.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_config_variables_variable_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_pipeline_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_pipeline_uuid_steps.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pipelines_pipeline_uuid_steps_step_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_properties_app_key_property_name.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pull_request_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pull_request_id_comments.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pull_request_id_comments_comment_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pull_request_id_statuses.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks_task_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_pullrequests_pullrequest_id_properties_app_key_property_name.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_refs.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_refs_branches.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_refs_branches_name.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_refs_tags.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_refs_tags_name.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_src.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_versions.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_versions_version_id.json",
			"internal/connectors/defs/bitbucket/schemas/repositories_workspace_repo_slug_watchers.json",
			"internal/connectors/defs/bitbucket/schemas/snippets.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id_comments.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id_comments_comment_id.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id_commits.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id_commits_revision.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id_node_id.json",
			"internal/connectors/defs/bitbucket/schemas/snippets_workspace_encoded_id_watchers.json",
			"internal/connectors/defs/bitbucket/schemas/teams_username_pipelines_config_variables.json",
			"internal/connectors/defs/bitbucket/schemas/teams_username_pipelines_config_variables_variable_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/user.json",
			"internal/connectors/defs/bitbucket/schemas/user_permissions_repositories.json",
			"internal/connectors/defs/bitbucket/schemas/user_permissions_workspaces.json",
			"internal/connectors/defs/bitbucket/schemas/user_workspaces.json",
			"internal/connectors/defs/bitbucket/schemas/user_workspaces_workspace_permission.json",
			"internal/connectors/defs/bitbucket/schemas/user_workspaces_workspace_permissions_repositories.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_gpg_keys.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_gpg_keys_fingerprint.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_pipelines_config_variables.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_pipelines_config_variables_variable_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_properties_app_key_property_name.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_ssh_keys.json",
			"internal/connectors/defs/bitbucket/schemas/users_selected_user_ssh_keys_key_id.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_hooks.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_hooks_uid.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_members.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_members_member.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_permissions.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_permissions_repositories.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_permissions_repositories_repo_slug.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_pipelines_config_runners.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_pipelines_config_runners_runner_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_pipelines_config_variables.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_pipelines_config_variables_variable_uuid.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_branching_model.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_branching_model_settings.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_default_reviewers.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_default_reviewers_selected_user.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_deploy_keys.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_deploy_keys_key_id.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_permissions_config_groups.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_permissions_config_groups_group_slug.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_permissions_config_users.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_projects_project_key_permissions_config_users_selected_user_id.json",
			"internal/connectors/defs/bitbucket/schemas/workspaces_workspace_pullrequests_selected_user.json",
			"internal/connectors/defs/bitbucket/spec.json",
			"internal/connectors/defs/bitbucket/streams.json",
			"internal/connectors/defs/bitbucket/writes.json",
			"internal/connectors/engine/bundle.go",
			"internal/connectors/engine/connector.go",
			"internal/connectors/engine/schema/cli_surface.schema.json",
			"internal/connectors/manifest.go",
			"website/content/docs/reverse-etl.mdx",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
			"website/lib/connectors.catalog.generated.ts",
			"website/lib/connectors.generated.ts",
			"website/lib/docs.generated.ts",
		},
	},
	{
		name:               "zendesk-support",
		mergeCommit:        "e99d6f1193814d00bd1b0c09fc092639d4fd8c54",
		connector:          "zendesk-support",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/zendesk-support.scope.json",
		wantScopedFindings: 24,
		wantAutoFindings:   1,
		changedPaths: []string{
			".planning/phases/issue-156-zendesk-support-parity/PLAN.md",
			".planning/phases/issue-156-zendesk-support-parity/RUN-STATE.json",
			".planning/phases/issue-156-zendesk-support-parity/SUMMARY.md",
			".planning/phases/issue-156-zendesk-support-parity/TDD-LEDGER.md",
			".planning/phases/issue-156-zendesk-support-parity/VERIFICATION.md",
			"docs/connectors/README.md",
			"docs/connectors/bahmni/MANUAL.md",
			"docs/connectors/bahmni/SKILL.md",
			"docs/connectors/bitbucket/MANUAL.md",
			"docs/connectors/bitbucket/SKILL.md",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/gong/MANUAL.md",
			"docs/connectors/gong/SKILL.md",
			"docs/connectors/hubspot/MANUAL.md",
			"docs/connectors/hubspot/SKILL.md",
			"docs/connectors/xero/MANUAL.md",
			"docs/connectors/xero/SKILL.md",
			"docs/connectors/zendesk-support/MANUAL.md",
			"docs/connectors/zendesk-support/SKILL.md",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/connectors.go",
			"internal/connectors/defs/zendesk-support/api_surface.json",
			"internal/connectors/defs/zendesk-support/cli_surface.json",
			"internal/connectors/defs/zendesk-support/docs.md",
			"internal/connectors/defs/zendesk-support/metadata.json",
			"internal/connectors/defs/zendesk-support/operations.json",
			"internal/connectors/guide.go",
			"internal/connectors/guide_test.go",
			"website/app/api/raw/[...slug]/route.ts",
			"website/app/api/search/route.ts",
			"website/app/docs/connectors/[slug]/page.tsx",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
			"website/lib/connectors.types.ts",
			"website/scripts/lib/cli-surface.mjs",
			"website/tests/api/connector-data.test.ts",
		},
	},
	{
		name:               "google-ads",
		mergeCommit:        "5d61794f76c46ca256280eb4166c5285c4b68731",
		connector:          "google-ads",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/google-ads.scope.json",
		wantScopedFindings: 16,
		wantAutoFindings:   1,
		changedPaths: []string{
			".planning/phases/google-ads-parity-wave03-r1/ISSUE-ADDENDUM.md",
			".planning/phases/google-ads-parity-wave03-r1/PLAN.md",
			".planning/phases/google-ads-parity-wave03-r1/RUN-STATE.json",
			".planning/phases/google-ads-parity-wave03-r1/SOURCE-AUDIT.json",
			".planning/phases/google-ads-parity-wave03-r1/SOURCE-AUDIT.md",
			".planning/phases/google-ads-parity-wave03-r1/TDD-LEDGER.md",
			".planning/phases/google-ads-parity-wave03-r1/VERIFICATION.md",
			".planning/phases/google-ads-parity-wave03-r1/generate_google_ads_parity.py",
			"cmd/connectorgen/main.go",
			"cmd/connectorgen/main_test.go",
			"cmd/connectorgen/validate.go",
			"docs/connectors/README.md",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/catalog/all-connectors.md",
			"docs/connectors/google-ads/MANUAL.md",
			"docs/connectors/google-ads/SKILL.md",
			"docs/migration/conventions.md",
			"internal/cli/cli.go",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/command_surface.go",
			"internal/connectors/commandrunner/runner.go",
			"internal/connectors/commandrunner/runner_test.go",
			"internal/connectors/defs/gong/cli_surface.json",
			"internal/connectors/defs/google-ads/api_surface.json",
			"internal/connectors/defs/google-ads/cli_surface.json",
			"internal/connectors/defs/google-ads/docs.md",
			"internal/connectors/defs/google-ads/fixtures/check.json",
			"internal/connectors/defs/google-ads/fixtures/streams/accessible_customers/page_1.json",
			"internal/connectors/defs/google-ads/fixtures/streams/ad_groups/page_1.json",
			"internal/connectors/defs/google-ads/fixtures/streams/campaigns/page_1.json",
			"internal/connectors/defs/google-ads/fixtures/writes/move_manager_link_customer_manager_links.json",
			"internal/connectors/defs/google-ads/fixtures/writes/remove_data_links.json",
			"internal/connectors/defs/google-ads/fixtures/writes/remove_product_link_invitations.json",
			"internal/connectors/defs/google-ads/fixtures/writes/remove_product_links.json",
			"internal/connectors/defs/google-ads/fixtures/writes/start_identity_verification_customers.json",
			"internal/connectors/defs/google-ads/fixtures/writes/update_data_links.json",
			"internal/connectors/defs/google-ads/fixtures/writes/update_product_link_invitations.json",
			"internal/connectors/defs/google-ads/metadata.json",
			"internal/connectors/defs/google-ads/operations.json",
			"internal/connectors/defs/google-ads/spec.json",
			"internal/connectors/defs/google-ads/streams.json",
			"internal/connectors/defs/google-ads/writes.json",
			"internal/connectors/engine/bundle.go",
			"internal/connectors/engine/connector.go",
			"internal/connectors/engine/schema/cli_surface.schema.json",
			"internal/connectors/guide.go",
			"internal/connectors/hooks/google-ads/hooks.go",
			"internal/connectors/hooks/google-ads/hooks_test.go",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
			"website/lib/connectors.catalog.generated.ts",
			"website/lib/connectors.types.ts",
			"website/scripts/lib/cli-surface.mjs",
		},
	},
	{
		name:               "freshchat",
		mergeCommit:        "b053dc4a3ad7930738cd719357178e90e8dda333",
		connector:          "freshchat",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/freshchat.scope.json",
		wantScopedFindings: 2,
		wantAutoFindings:   2,
		changedPaths: []string{
			".planning/phases/issue-180-freshchat-parity-wave02-r1/PLAN.md",
			".planning/phases/issue-180-freshchat-parity-wave02-r1/PROMPTS.md",
			".planning/phases/issue-180-freshchat-parity-wave02-r1/RUN-STATE.json",
			".planning/phases/issue-180-freshchat-parity-wave02-r1/SUMMARY.md",
			".planning/phases/issue-180-freshchat-parity-wave02-r1/TDD-LEDGER.md",
			".planning/phases/issue-180-freshchat-parity-wave02-r1/VERIFICATION.md",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/freshchat/MANUAL.md",
			"docs/connectors/freshchat/SKILL.md",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/commandrunner/runner.go",
			"internal/connectors/commandrunner/runner_test.go",
			"internal/connectors/defs/freshchat/api_surface.json",
			"internal/connectors/defs/freshchat/certification.json",
			"internal/connectors/defs/freshchat/cli_surface.json",
			"internal/connectors/defs/freshchat/docs.md",
			"internal/connectors/defs/freshchat/spec.json",
			"internal/connectors/defs/freshchat/streams.json",
			"internal/connectors/defs/freshchat/writes.json",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
		},
	},
	{
		name:               "xero",
		mergeCommit:        "2685c3712a9677cf0f74864edf79474b823db55e",
		connector:          "xero",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/xero.scope.json",
		wantScopedFindings: 0,
		wantAutoFindings:   0,
		changedPaths: []string{
			".planning/phases/xero-parity-wave04-r1/ISSUE-ADDENDUM.md",
			".planning/phases/xero-parity-wave04-r1/PLAN.md",
			".planning/phases/xero-parity-wave04-r1/RUN-STATE.json",
			".planning/phases/xero-parity-wave04-r1/TDD-LEDGER.md",
			".planning/phases/xero-parity-wave04-r1/VERIFICATION.md",
			"cmd/connectorgen/xero_api_surface_test.go",
			"docs/connectors/catalog/all-connectors.json",
			"docs/connectors/catalog/all-connectors.md",
			"docs/connectors/xero/MANUAL.md",
			"docs/connectors/xero/SKILL.md",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/defs/xero/api_surface.json",
			"internal/connectors/defs/xero/certification.json",
			"internal/connectors/defs/xero/cli_surface.json",
			"internal/connectors/defs/xero/docs.md",
			"internal/connectors/defs/xero/fixtures/check.json",
			"internal/connectors/defs/xero/fixtures/streams/account/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/account_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/accounts/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transaction/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transaction_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transactions/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transactions_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transfer/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transfer_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transfer_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/bank_transfers/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/batch_payment/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/batch_payment_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/batch_payments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/branding_theme/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/branding_theme_payment_services/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/branding_themes/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/budget/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/budgets/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact_by_contact_number/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact_cis_settings/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact_group/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact_groups/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contact_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/contacts/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/credit_note/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/credit_note_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/credit_note_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/credit_notes/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/currencies/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/expense_claim/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/expense_claim_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/expense_claims/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/invoice/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/invoice_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/invoice_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/invoice_reminders/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/invoices/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/invoices/page_2.json",
			"internal/connectors/defs/xero/fixtures/streams/item/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/item_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/items/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/journal/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/journal_by_number/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/journals/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/linked_transaction/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/linked_transactions/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/manual_journal/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/manual_journal_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/manual_journals/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/manual_journals_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/online_invoice/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/organisation_actions/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/organisation_cis_settings/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/organisations/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/overpayment/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/overpayment_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/overpayments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/payment/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/payment_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/payment_services/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/payments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/prepayment/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/prepayment_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/prepayments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/purchase_order/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/purchase_order_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/purchase_order_by_number/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/purchase_order_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/purchase_orders/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/quote/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/quote_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/quote_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/quotes/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/receipt/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/receipt_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/receipt_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/receipts/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/repeating_invoice/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/repeating_invoice_attachments/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/repeating_invoice_history/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/repeating_invoices/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_aged_payables_by_contact/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_aged_receivables_by_contact/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_balance_sheet/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_bank_summary/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_budget_summary/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_executive_summary/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_from_id/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_profit_and_loss/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_ten_ninety_nine/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/report_trial_balance/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/reports_list/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/tax_rate_by_tax_type/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/tax_rates/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/tracking_categories/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/tracking_category/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/user/page_1.json",
			"internal/connectors/defs/xero/fixtures/streams/users/page_1.json",
			"internal/connectors/defs/xero/fixtures/writes/create_account.json",
			"internal/connectors/defs/xero/fixtures/writes/create_bank_transaction_history_record.json",
			"internal/connectors/defs/xero/fixtures/writes/create_bank_transactions.json",
			"internal/connectors/defs/xero/fixtures/writes/create_bank_transfer.json",
			"internal/connectors/defs/xero/fixtures/writes/create_bank_transfer_history_record.json",
			"internal/connectors/defs/xero/fixtures/writes/create_batch_payment.json",
			"internal/connectors/defs/xero/fixtures/writes/create_batch_payment_history_record.json",
			"internal/connectors/defs/xero/fixtures/writes/create_branding_theme_payment_services.json",
			"internal/connectors/defs/xero/fixtures/writes/create_contact_group.json",
			"internal/connectors/defs/xero/fixtures/writes/create_contact_group_contacts.json",
			"internal/connectors/defs/xero/fixtures/writes/create_contact_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_contacts.json",
			"internal/connectors/defs/xero/fixtures/writes/create_credit_note_allocation.json",
			"internal/connectors/defs/xero/fixtures/writes/create_credit_note_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_credit_notes.json",
			"internal/connectors/defs/xero/fixtures/writes/create_currency.json",
			"internal/connectors/defs/xero/fixtures/writes/create_expense_claim_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_expense_claims.json",
			"internal/connectors/defs/xero/fixtures/writes/create_invoice_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_invoices.json",
			"internal/connectors/defs/xero/fixtures/writes/create_item_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_items.json",
			"internal/connectors/defs/xero/fixtures/writes/create_linked_transaction.json",
			"internal/connectors/defs/xero/fixtures/writes/create_manual_journal_history_record.json",
			"internal/connectors/defs/xero/fixtures/writes/create_manual_journals.json",
			"internal/connectors/defs/xero/fixtures/writes/create_overpayment_allocations.json",
			"internal/connectors/defs/xero/fixtures/writes/create_overpayment_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_payment.json",
			"internal/connectors/defs/xero/fixtures/writes/create_payment_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_payment_service.json",
			"internal/connectors/defs/xero/fixtures/writes/create_payments.json",
			"internal/connectors/defs/xero/fixtures/writes/create_prepayment_allocations.json",
			"internal/connectors/defs/xero/fixtures/writes/create_prepayment_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_purchase_order_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_purchase_orders.json",
			"internal/connectors/defs/xero/fixtures/writes/create_quote_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_quotes.json",
			"internal/connectors/defs/xero/fixtures/writes/create_receipt.json",
			"internal/connectors/defs/xero/fixtures/writes/create_receipt_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_repeating_invoice_history.json",
			"internal/connectors/defs/xero/fixtures/writes/create_repeating_invoices.json",
			"internal/connectors/defs/xero/fixtures/writes/create_tax_rates.json",
			"internal/connectors/defs/xero/fixtures/writes/create_tracking_category.json",
			"internal/connectors/defs/xero/fixtures/writes/create_tracking_options.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_account.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_bank_transfer.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_bank_transfers.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_batch_payment.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_batch_payment_by_url_param.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_contact_group_contact.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_contact_group_contacts.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_credit_note_allocations.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_item.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_linked_transaction.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_overpayment_allocations.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_payment.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_prepayment_allocations.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_tracking_category.json",
			"internal/connectors/defs/xero/fixtures/writes/delete_tracking_options.json",
			"internal/connectors/defs/xero/fixtures/writes/email_invoice.json",
			"internal/connectors/defs/xero/fixtures/writes/setup_organisation.json",
			"internal/connectors/defs/xero/fixtures/writes/update_account.json",
			"internal/connectors/defs/xero/fixtures/writes/update_bank_transaction.json",
			"internal/connectors/defs/xero/fixtures/writes/update_contact.json",
			"internal/connectors/defs/xero/fixtures/writes/update_contact_group.json",
			"internal/connectors/defs/xero/fixtures/writes/update_credit_note.json",
			"internal/connectors/defs/xero/fixtures/writes/update_expense_claim.json",
			"internal/connectors/defs/xero/fixtures/writes/update_invoice.json",
			"internal/connectors/defs/xero/fixtures/writes/update_item.json",
			"internal/connectors/defs/xero/fixtures/writes/update_linked_transaction.json",
			"internal/connectors/defs/xero/fixtures/writes/update_manual_journal.json",
			"internal/connectors/defs/xero/fixtures/writes/update_purchase_order.json",
			"internal/connectors/defs/xero/fixtures/writes/update_quote.json",
			"internal/connectors/defs/xero/fixtures/writes/update_receipt.json",
			"internal/connectors/defs/xero/fixtures/writes/update_repeating_invoice.json",
			"internal/connectors/defs/xero/fixtures/writes/update_tax_rate.json",
			"internal/connectors/defs/xero/fixtures/writes/update_tracking_category.json",
			"internal/connectors/defs/xero/fixtures/writes/update_tracking_options.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_bank_transactions.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_contacts.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_credit_notes.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_invoices.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_items.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_manual_journals.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_purchase_orders.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_quotes.json",
			"internal/connectors/defs/xero/fixtures/writes/upsert_repeating_invoices.json",
			"internal/connectors/defs/xero/operations.json",
			"internal/connectors/defs/xero/writes.json",
			"internal/connectors/engine/xero_operations_test.go",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
		},
	},
	{
		name:               "asana",
		mergeCommit:        "fc07dc8303427b781b86f942f2bc8fe756bd8d45",
		connector:          "asana",
		scopeFile:          "internal/connectors/boundary/testdata/ownership-corpus/asana.scope.json",
		wantScopedFindings: 0,
		wantAutoFindings:   0,
		changedPaths: []string{
			".planning/phases/issue-380-asana-parity/PLAN.md",
			".planning/phases/issue-380-asana-parity/RUN-STATE.json",
			".planning/phases/issue-380-asana-parity/SUMMARY.md",
			".planning/phases/issue-380-asana-parity/TDD-LEDGER.md",
			".planning/phases/issue-380-asana-parity/VERIFICATION.md",
			".planning/phases/issue-380-asana-parity/traces/gsd-plan-phase-380.prompt.md",
			".planning/phases/issue-380-asana-parity/traces/gsd-programming-loop.stderr",
			".planning/phases/issue-380-asana-parity/traces/gsd-quick-full.prompt.md",
			"docs/connectors/README.md",
			"docs/connectors/asana/MANUAL.md",
			"docs/connectors/asana/SKILL.md",
			"docs/connectors/catalog/all-connectors.json",
			"internal/cli/testdata/golden_transcripts.json",
			"internal/connectors/defs/asana/api_surface.json",
			"internal/connectors/defs/asana/certification.json",
			"internal/connectors/defs/asana/cli_surface.json",
			"internal/connectors/defs/asana/docs.md",
			"internal/connectors/defs/asana/metadata.json",
			"internal/connectors/defs/asana/operations.json",
			"internal/connectors/defs/asana/writes.json",
			"website/data/connectors.generated.json",
			"website/lib/connectors.catalog.data.generated.json",
		},
	}}

// TestOwnershipCorpusMatchesAuditedMergeCommits is the required regression
// coverage: it replays the real changed-path set from each audited merge
// commit with an explicit scope file (as a labeled connector PR would) and
// asserts the exact finding count, so a future recalibration cannot
// silently widen the allowlists past what the audit certified.
func TestOwnershipCorpusMatchesAuditedMergeCommits(t *testing.T) {
	root := findRepoRoot(t)
	for _, tt := range ownershipCorpusCases {
		t.Run(tt.name, func(t *testing.T) {
			report, err := ValidateOwnership(root, OwnershipOptions{
				ScopeFile:    tt.scopeFile,
				ChangedPaths: tt.changedPaths,
				Now:          fixedNow,
			})
			if err != nil {
				t.Fatalf("ValidateOwnership(%s @ %s): %v", tt.name, tt.mergeCommit, err)
			}
			if len(report.Findings) != tt.wantScopedFindings {
				t.Fatalf("%s @ %s: findings = %d, want %d\n%+v", tt.name, tt.mergeCommit, len(report.Findings), tt.wantScopedFindings, report.Findings)
			}
			wantOutcome := OutcomeClean
			if tt.wantScopedFindings > 0 {
				wantOutcome = OutcomePolicyViolations
			}
			if report.Outcome != wantOutcome {
				t.Fatalf("%s @ %s: outcome = %q, want %q", tt.name, tt.mergeCommit, report.Outcome, wantOutcome)
			}
			if report.TargetConnector != tt.connector {
				t.Fatalf("%s @ %s: target connector = %q, want %q", tt.name, tt.mergeCommit, report.TargetConnector, tt.connector)
			}
		})
	}
}

// TestOwnershipCorpusAutoDetectsTargetWithoutScopeFile verifies the
// label/manifest-omission property: connector implementation diffs must be
// auto-detected from changed paths alone, so a connector PR that omits its
// scope file/label cannot skip enforcement. It replays the same eight real
// merge commits with no scope file at all.
func TestOwnershipCorpusAutoDetectsTargetWithoutScopeFile(t *testing.T) {
	root := findRepoRoot(t)
	for _, tt := range ownershipCorpusCases {
		t.Run(tt.name, func(t *testing.T) {
			report, err := ValidateOwnership(root, OwnershipOptions{
				ChangedPaths: tt.changedPaths,
				Now:          fixedNow,
			})
			if err != nil {
				t.Fatalf("ValidateOwnership(%s @ %s): %v", tt.name, tt.mergeCommit, err)
			}
			if len(report.Findings) != tt.wantAutoFindings {
				t.Fatalf("%s @ %s: auto-detect findings = %d, want %d\n%+v", tt.name, tt.mergeCommit, len(report.Findings), tt.wantAutoFindings, report.Findings)
			}
			wantOutcome := OutcomeClean
			if tt.wantAutoFindings > 0 {
				wantOutcome = OutcomePolicyViolations
			}
			if report.Outcome != wantOutcome {
				t.Fatalf("%s @ %s: auto-detect outcome = %q, want %q", tt.name, tt.mergeCommit, report.Outcome, wantOutcome)
			}
		})
	}
}
