// Code generated by connectorgen gen. DO NOT EDIT.
//
// Package hookset blank-imports every internal/connectors/hooks/<name>
// package so their init() functions run engine.RegisterHooks side effects.
// It is regenerated deterministically by `go run ./cmd/connectorgen gen`.
package hookset

import (
	_ "polymetrics.ai/internal/connectors/hooks/github"
	_ "polymetrics.ai/internal/connectors/hooks/gmail"
	_ "polymetrics.ai/internal/connectors/hooks/monday"
	_ "polymetrics.ai/internal/connectors/hooks/sentry"
)
