// Code generated by connectorgen gen. DO NOT EDIT.
//
// Package hookset supplies explicit hook factories for production construction.
// It is regenerated deterministically by `go run ./cmd/connectorgen gen`.
package hookset

import (
	"polymetrics.ai/internal/connectors/engine"
	akeneo "polymetrics.ai/internal/connectors/hooks/akeneo"
	amazon_ads "polymetrics.ai/internal/connectors/hooks/amazon-ads"
	amazon_seller_partner "polymetrics.ai/internal/connectors/hooks/amazon-seller-partner"
	apple_search_ads "polymetrics.ai/internal/connectors/hooks/apple-search-ads"
	appsflyer "polymetrics.ai/internal/connectors/hooks/appsflyer"
	blogger "polymetrics.ai/internal/connectors/hooks/blogger"
	chift "polymetrics.ai/internal/connectors/hooks/chift"
	ebay_fulfillment "polymetrics.ai/internal/connectors/hooks/ebay-fulfillment"
	elasticsearch "polymetrics.ai/internal/connectors/hooks/elasticsearch"
	feishu "polymetrics.ai/internal/connectors/hooks/feishu"
	github "polymetrics.ai/internal/connectors/hooks/github"
	gmail "polymetrics.ai/internal/connectors/hooks/gmail"
	google_ads "polymetrics.ai/internal/connectors/hooks/google-ads"
	google_calendar "polymetrics.ai/internal/connectors/hooks/google-calendar"
	google_forms "polymetrics.ai/internal/connectors/hooks/google-forms"
	google_search_console "polymetrics.ai/internal/connectors/hooks/google-search-console"
	hoorayhr "polymetrics.ai/internal/connectors/hooks/hoorayhr"
	jamf_pro "polymetrics.ai/internal/connectors/hooks/jamf-pro"
	keka "polymetrics.ai/internal/connectors/hooks/keka"
	microsoft_dataverse "polymetrics.ai/internal/connectors/hooks/microsoft-dataverse"
	microsoft_entra_id "polymetrics.ai/internal/connectors/hooks/microsoft-entra-id"
	microsoft_lists "polymetrics.ai/internal/connectors/hooks/microsoft-lists"
	microsoft_teams "polymetrics.ai/internal/connectors/hooks/microsoft-teams"
	mixpanel "polymetrics.ai/internal/connectors/hooks/mixpanel"
	monday "polymetrics.ai/internal/connectors/hooks/monday"
	netsuite "polymetrics.ai/internal/connectors/hooks/netsuite"
	nexus_datasets "polymetrics.ai/internal/connectors/hooks/nexus-datasets"
	notion "polymetrics.ai/internal/connectors/hooks/notion"
	outlook "polymetrics.ai/internal/connectors/hooks/outlook"
	paypal_transaction "polymetrics.ai/internal/connectors/hooks/paypal-transaction"
	pinterest "polymetrics.ai/internal/connectors/hooks/pinterest"
	plaid "polymetrics.ai/internal/connectors/hooks/plaid"
	quickbooks "polymetrics.ai/internal/connectors/hooks/quickbooks"
	rss "polymetrics.ai/internal/connectors/hooks/rss"
	salesloft "polymetrics.ai/internal/connectors/hooks/salesloft"
	sentry "polymetrics.ai/internal/connectors/hooks/sentry"
	serpstat "polymetrics.ai/internal/connectors/hooks/serpstat"
	slack "polymetrics.ai/internal/connectors/hooks/slack"
	smartsheets "polymetrics.ai/internal/connectors/hooks/smartsheets"
	snapchat_marketing "polymetrics.ai/internal/connectors/hooks/snapchat-marketing"
	stigg "polymetrics.ai/internal/connectors/hooks/stigg"
	strava "polymetrics.ai/internal/connectors/hooks/strava"
	twilio "polymetrics.ai/internal/connectors/hooks/twilio"
	uptick "polymetrics.ai/internal/connectors/hooks/uptick"
	us_census "polymetrics.ai/internal/connectors/hooks/us-census"
	wasabi_stats_api "polymetrics.ai/internal/connectors/hooks/wasabi-stats-api"
	youtube_analytics "polymetrics.ai/internal/connectors/hooks/youtube-analytics"
	zoho_analytics_metadata_api "polymetrics.ai/internal/connectors/hooks/zoho-analytics-metadata-api"
	zoho_bigin "polymetrics.ai/internal/connectors/hooks/zoho-bigin"
)

// Factory constructs one connector-owned hook set selected by an exact generated extension ID.
type Factory struct {
	ID string
	Connector string
	New func() engine.Hooks
}

// Factories returns the closed, deterministic production hook inventory.
func Factories() []Factory {
	return []Factory{
		{ID: "hook/akeneo.v1", Connector: "akeneo", New: akeneo.ExplicitFactory},
		{ID: "hook/amazon-ads.v1", Connector: "amazon-ads", New: amazon_ads.ExplicitFactory},
		{ID: "hook/amazon-seller-partner.v1", Connector: "amazon-seller-partner", New: amazon_seller_partner.ExplicitFactory},
		{ID: "hook/apple-search-ads.v1", Connector: "apple-search-ads", New: apple_search_ads.ExplicitFactory},
		{ID: "hook/appsflyer.v1", Connector: "appsflyer", New: appsflyer.ExplicitFactory},
		{ID: "hook/blogger.v1", Connector: "blogger", New: blogger.ExplicitFactory},
		{ID: "hook/chift.v1", Connector: "chift", New: chift.ExplicitFactory},
		{ID: "hook/ebay-fulfillment.v1", Connector: "ebay-fulfillment", New: ebay_fulfillment.ExplicitFactory},
		{ID: "hook/elasticsearch.v1", Connector: "elasticsearch", New: elasticsearch.ExplicitFactory},
		{ID: "hook/feishu.v1", Connector: "feishu", New: feishu.ExplicitFactory},
		{ID: "hook/github.v1", Connector: "github", New: github.ExplicitFactory},
		{ID: "hook/gmail.v1", Connector: "gmail", New: gmail.ExplicitFactory},
		{ID: "hook/google-ads.v1", Connector: "google-ads", New: google_ads.ExplicitFactory},
		{ID: "hook/google-calendar.v1", Connector: "google-calendar", New: google_calendar.ExplicitFactory},
		{ID: "hook/google-forms.v1", Connector: "google-forms", New: google_forms.ExplicitFactory},
		{ID: "hook/google-search-console.v1", Connector: "google-search-console", New: google_search_console.ExplicitFactory},
		{ID: "hook/hoorayhr.v1", Connector: "hoorayhr", New: hoorayhr.ExplicitFactory},
		{ID: "hook/jamf-pro.v1", Connector: "jamf-pro", New: jamf_pro.ExplicitFactory},
		{ID: "hook/keka.v1", Connector: "keka", New: keka.ExplicitFactory},
		{ID: "hook/microsoft-dataverse.v1", Connector: "microsoft-dataverse", New: microsoft_dataverse.ExplicitFactory},
		{ID: "hook/microsoft-entra-id.v1", Connector: "microsoft-entra-id", New: microsoft_entra_id.ExplicitFactory},
		{ID: "hook/microsoft-lists.v1", Connector: "microsoft-lists", New: microsoft_lists.ExplicitFactory},
		{ID: "hook/microsoft-teams.v1", Connector: "microsoft-teams", New: microsoft_teams.ExplicitFactory},
		{ID: "hook/mixpanel.v1", Connector: "mixpanel", New: mixpanel.ExplicitFactory},
		{ID: "hook/monday.v1", Connector: "monday", New: monday.ExplicitFactory},
		{ID: "hook/netsuite.v1", Connector: "netsuite", New: netsuite.ExplicitFactory},
		{ID: "hook/nexus-datasets.v1", Connector: "nexus-datasets", New: nexus_datasets.ExplicitFactory},
		{ID: "hook/notion.v1", Connector: "notion", New: notion.ExplicitFactory},
		{ID: "hook/outlook.v1", Connector: "outlook", New: outlook.ExplicitFactory},
		{ID: "hook/paypal-transaction.v1", Connector: "paypal-transaction", New: paypal_transaction.ExplicitFactory},
		{ID: "hook/pinterest.v1", Connector: "pinterest", New: pinterest.ExplicitFactory},
		{ID: "hook/plaid.v1", Connector: "plaid", New: plaid.ExplicitFactory},
		{ID: "hook/quickbooks.v1", Connector: "quickbooks", New: quickbooks.ExplicitFactory},
		{ID: "hook/rss.v1", Connector: "rss", New: rss.ExplicitFactory},
		{ID: "hook/salesloft.v1", Connector: "salesloft", New: salesloft.ExplicitFactory},
		{ID: "hook/sentry.v1", Connector: "sentry", New: sentry.ExplicitFactory},
		{ID: "hook/serpstat.v1", Connector: "serpstat", New: serpstat.ExplicitFactory},
		{ID: "hook/slack.v1", Connector: "slack", New: slack.ExplicitFactory},
		{ID: "hook/smartsheets.v1", Connector: "smartsheets", New: smartsheets.ExplicitFactory},
		{ID: "hook/snapchat-marketing.v1", Connector: "snapchat-marketing", New: snapchat_marketing.ExplicitFactory},
		{ID: "hook/stigg.v1", Connector: "stigg", New: stigg.ExplicitFactory},
		{ID: "hook/strava.v1", Connector: "strava", New: strava.ExplicitFactory},
		{ID: "hook/twilio.v1", Connector: "twilio", New: twilio.ExplicitFactory},
		{ID: "hook/uptick.v1", Connector: "uptick", New: uptick.ExplicitFactory},
		{ID: "hook/us-census.v1", Connector: "us-census", New: us_census.ExplicitFactory},
		{ID: "hook/wasabi-stats-api.v1", Connector: "wasabi-stats-api", New: wasabi_stats_api.ExplicitFactory},
		{ID: "hook/youtube-analytics.v1", Connector: "youtube-analytics", New: youtube_analytics.ExplicitFactory},
		{ID: "hook/zoho-analytics-metadata-api.v1", Connector: "zoho-analytics-metadata-api", New: zoho_analytics_metadata_api.ExplicitFactory},
		{ID: "hook/zoho-bigin.v1", Connector: "zoho-bigin", New: zoho_bigin.ExplicitFactory},
	}
}
