// Code generated by agentcontractgen; DO NOT EDIT.

package certificationcatalog

func init() {
	registerGeneratedFlowKinds([]FlowKind{
		{ID: "api_to_api", SourceRole: "api_source", DestinationRole: "api_destination"},
		{ID: "api_to_database", SourceRole: "api_source", DestinationRole: "database_destination"},
		{ID: "database_to_api", SourceRole: "database_source", DestinationRole: "api_destination"},
		{ID: "database_to_database", SourceRole: "database_source", DestinationRole: "database_destination"},
	})
}
