// Command registrygen regenerates internal/connectors/registryset/registry_gen.go
// by scanning internal/connectors/<name>/ for connector packages and emitting a
// blank import for each. Connector packages self-register via init() ->
// connectors.RegisterFactory; this tool only wires the imports so those init()
// side effects run in the built binary.
//
// Because registration is DERIVED from which package directories exist, many
// connectors can be authored in parallel (each in its own directory) without any
// of them editing the shared registry file. Run this once at convergence:
//
//	go run ./cmd/registrygen
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	connectorsRel = "internal/connectors"
	outRel        = "internal/connectors/registryset/registry_gen.go"
	modulePath    = "polymetrics/internal/connectors"
)

// skip lists directories under internal/connectors that are not connector
// packages (the shared SDK and the wiring package itself).
var skip = map[string]bool{
	"connsdk":     true,
	"registryset": true,
}

func main() {
	root, err := repoRoot()
	if err != nil {
		fail(err)
	}
	pkgs, err := connectorPackages(filepath.Join(root, connectorsRel))
	if err != nil {
		fail(err)
	}
	if err := writeRegistry(filepath.Join(root, outRel), pkgs); err != nil {
		fail(err)
	}
	fmt.Printf("registrygen: wrote %d connector imports to %s\n", len(pkgs), outRel)
}

// repoRoot finds the module root by walking up to the directory containing go.mod.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from working directory")
		}
		dir = parent
	}
}

// connectorPackages returns the sorted directory names under connectorsDir that
// declare a connector package (any non-test .go file with a package clause). The
// emitted blank import keys off the import path, not the package identifier, so a
// directory whose declared package name is sanitized (e.g. dir "amazon-ads" with
// package "amazonads", or "100ms" with package "onehms") is still wired in. This
// keeps connectors reachable by their bare registry name regardless of how the
// hyphenated/digit-leading directory was turned into a valid Go identifier.
func connectorPackages(connectorsDir string) ([]string, error) {
	entries, err := os.ReadDir(connectorsDir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", connectorsDir, err)
	}
	var pkgs []string
	for _, entry := range entries {
		if !entry.IsDir() || skip[entry.Name()] {
			continue
		}
		ok, err := declaresPackage(filepath.Join(connectorsDir, entry.Name()))
		if err != nil {
			return nil, err
		}
		if ok {
			pkgs = append(pkgs, entry.Name())
		}
	}
	sort.Strings(pkgs)
	return pkgs, nil
}

// declaresPackage reports whether dir contains a non-test .go file that declares
// a Go package. The package identifier need not match the directory name, since
// connector directories with hyphens or leading digits must sanitize their
// package clause to a valid identifier.
func declaresPackage(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", dir, err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return false, fmt.Errorf("read %s: %w", filepath.Join(dir, name), err)
		}
		if packageClause(data) != "" {
			return true, nil
		}
	}
	return false, nil
}

// packageClause extracts the package name from Go source, skipping comments and
// build-constraint/blank lines.
func packageClause(src []byte) string {
	for _, line := range strings.Split(string(src), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") || strings.HasPrefix(trimmed, "*") {
			continue
		}
		if strings.HasPrefix(trimmed, "package ") {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, "package "))
		}
	}
	return ""
}

func writeRegistry(outPath string, pkgs []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/registrygen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Package registryset wires per-system connector packages into the connectors\n")
	b.WriteString("// registry. Each connector package self-registers via connectors.RegisterFactory\n")
	b.WriteString("// in its init(); the blank imports below run those init() side effects. This file\n")
	b.WriteString("// is regenerated by `go run ./cmd/registrygen` and must never be imported by\n")
	b.WriteString("// package connectors (which the connector packages depend on) to avoid a cycle.\n")
	b.WriteString("package registryset\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"" + modulePath + "\"\n")
	if len(pkgs) > 0 {
		b.WriteString("\n")
		for _, pkg := range pkgs {
			b.WriteString("\t_ \"" + modulePath + "/" + pkg + "\"\n")
		}
	}
	b.WriteString(")\n\n")
	b.WriteString("// New returns a connectors.Registry with every wired connector registered.\n")
	b.WriteString("func New() *connectors.Registry { return connectors.NewRegistry() }\n")
	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "registrygen:", err)
	os.Exit(1)
}
