name: Verify

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git defaults
        run: git config --global init.defaultBranch main

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
          cache: false

      - name: Verify
        run: make verify

      - name: Check generated files
        run: git diff --exit-code
